### ISSUE TITLE
fix: Adjust color scheme of the resume for light screen

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#1]
## Issue faced
Currently few sections of the product is not visible in light mode. Look into each file and adjust the colors accordingly.
We are currently using shadcn/ui for the UI and radix icons.

**Comment by VanshikaSabharwal** [comment]
i am ready to work on UI .can you assign this work to me. I am a GSSOC contributor

**Comment by ashutosh-rath02** [comment]
Sure @VanshikaSabharwal please let me know what you are planning to do and I can assign you the issue.

**Comment by Anayverma** [comment]
hey @ashutosh-rath02 please assign it to me under gssoc24. I want to work on it.

**Comment by VanshikaSabharwal** [comment]
Yes @ashutosh-rath02 ,
 I plan to start by reviewing the current color schemes in the sections that are problematic in light mode. I'll identify the specific contrasts that are not meeting accessibility or visibility standards. My approach will involve adjusting the color values to ensure that all elements are clearly visible in both light and dark modes. I'll make sure to test these adjustments across different devices and screen settings to ensure consistent visibility.     I am familiar with shadcn/ui and radix icons, so I'll leverage this experience to make effective and aesthetically pleasing adjustments. I will document my changes and provide updates for review.

**Comment by ashutosh-rath02** [comment]
Okay @VanshikaSabharwal you can start working on it..will assign you

**Comment by ashutosh-rath02** [comment]
@VanshikaSabharwal Any update?

**Comment by mohdjami** [comment]
Hi @ashutosh-rath02, I can start working on this issue.

My approach: I am going to use Next.js inbuilt Next-theme library to add dark mode from scratch into the website. I will add a button in the bottom left corner to switch the themes from light to dark and vise versa. The main part will be adding seperate tailwind for each component separately for light and dark mode which for which I will need some reviews for the UI which I will ask you before creating a PR by sharing a video.

Please assign this issue to me under GSSoC'24.

**Comment by ashutosh-rath02** [comment]
@mohdjami Currently we are using shadcn theme toggling which is causing an issue when we try to download resume as pdfs. It would be great if you write the themes from the scratch

**Comment by mohdjami** [comment]
Sure @ashutosh-rath02 , I will start working on it and if I need some help I'll ask you.

**Comment by mohdjami** [comment]
Hey @ashutosh-rath02, I am having some trouble setting up the application. I am having some error, can you guide me? I read and followed the docs carefully. I am recieving this error that URL with credentials cant conduct a request.

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #1 has been closed. Thank you for your contribution!
