### ISSUE TITLE
Positioning of the Icon - Light and Dark mode on the navbar section 

### ISSUE THREAD

**Issue by Varnika2526** [ashutosh-rath02/git-re#104]
Adding the icon of light and dark mode to the top could enhance the page and be more user-friendly.
Kindly Assign me this task under GSSOC'24

**Comment by Karankumar2004** [comment]
Hey @ashutosh-rath02  , I'm keen to contribute. Could you assign me this issue under GSSoc 24'?

**Comment by gupta-sujal** [comment]
hi @ashutosh-rath02 , I have experience in developing the above mode toggler from shadcn-ui. I can contribute to the project. Please assign me this issue

**Comment by ashutosh-rath02** [comment]
It's at correct position for now
