### ISSUE TITLE
Bug: Error Handling for Nonexistent GitHub Usernames

### ISSUE THREAD

**Issue by Sahilll15** [ashutosh-rath02/git-re#115]
**Description:**
When attempting to fetch data for a GitHub user, if the provided username does not exist, the application currently fails to display an appropriate error message. This results in confusion and frustration for users who encounter this issue, as they are left unsure why the data is not being retrieved.

**Expected Behavior:**
When a nonexistent username is provided for fetching GitHub data, the application should display a clear and informative error message, informing the user that the username does not exist or cannot be found. This will provide users with immediate feedback and guidance on how to proceed.

**Steps to Reproduce:**

Enter a nonexistent username in the GitHub data fetching feature.
Attempt to fetch data for the provided username.
Observe the lack of response or unclear error message indicating the issue.

**Proposed Solution:**
Implement robust error handling mechanisms to detect when a GitHub username does not exist or cannot be found. Upon encountering such a scenario, display an error message on the user interface indicating that the provided username is invalid or cannot be located. Additionally, consider providing suggestions or guidance on how users can verify the correctness of the username or troubleshoot the issue.

**Additional Notes:**

Ensure that the error message is user-friendly and provides actionable information to assist users in resolving the issue.
Test the error handling functionality thoroughly to validate its effectiveness across different scenarios of invalid or nonexistent usernames.

example image
![Screenshot 2024-05-14 at 3 06 56 AM](https://github.com/ashutosh-rath02/git-re/assets/109215419/aed972bc-de50-4ff8-8dda-d9f50feba3c9)

**Comment by ashutosh-rath02** [comment]
How are you gonna check non-existent usernames?

**Comment by Sahilll15** [comment]
# GitHub API Error Handling for Nonexistent Usernames

When attempting to fetch data for a GitHub user, if the provided username does not exist, the GitHub API returns a 404 status code with a message indicating "Not Found." This response means that the username does not match any user in GitHub's database.

To handle this scenario, you should add validation in your application to check for the 404 status code. When this status code is encountered, your application should display a user-friendly error message informing the user that the provided username does not exist.

### API Response for Nonexistent Username

```json
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/users/users#get-a-user"
}
