### ISSUE TITLE
Add Error Page for Invalid URL Construction

### ISSUE THREAD

**Issue by IbrahimDev00** [ashutosh-rath02/git-re#116]
I tried running my Github username multiple times but it showed a client side error.
Making a page to communicate this error within the theme of the website and redirecting them to the homepage.
![Screenshot 2024-05-14 084533](https://github.com/ashutosh-rath02/git-re/assets/147825977/23821dc2-6132-4024-a5fd-e4bb5b863f86)

**Comment by IbrahimDev00** [comment]
@ashutosh-rath02 I'm a GSSoc'24 contributor.
To effectively handle the "Invalid URL" error I would follow the following steps:
1.  create a new component to serve as the error page.
2. To handle the "Invalid URL" error and display the error page I would use the Next.js custom error handling by overriding the getInitialProps method.
3. Add Styling with Tailwind CSS.

**Comment by ashutosh-rath02** [comment]
Duplicate #62. You can comment there to work on it, if the other person is non-responsive
