### ISSUE TITLE
bug: public.recent_users null check/adding error handling

### ISSUE THREAD

**Issue by ratishjain12** [ashutosh-rath02/git-re#121]
Apparently there is no null check for recent.users fetching from supabase which is showing error if not users are present in recent.users.

I want to add a error handling instead of throwing error, here so that app works seamless.

![image](https://github.com/ashutosh-rath02/git-re/assets/43003421/ad861b37-4306-4f78-a2ef-736025064213)
@ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
Go ahead

**Comment by ratishjain12** [comment]
@ashutosh-rath02 should I show a message in recent users section if no recent users are there?

**Comment by ashutosh-rath02** [comment]
Recent users are already there in db. Didn't get your point

**Comment by ratishjain12** [comment]
like for local db recent.users are not there by default for users yeah like in deployed recent users will already be there
