### ISSUE TITLE
enhancement: add background to the website

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#123]
**Is your feature request related to a problem? Please describe.**
The current background of the website is too simple. Let's plan out adding some sassy background.

**Describe the solution you'd like**
Adding some backgrounds which will improve how the whole website looks.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn:
<br>GitHub:
<br>Discord:
<br>Twitter:

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by Azhar-0401** [comment]
i would like to resolve the issue ,kindly assign the issue to me under GGSOC'24 tag

**Comment by ashutosh-rath02** [comment]
@Azhar-0401 this issue needs to be discussed properly to choose a background. Can you provide some implementations on git-re that you propose?

**Comment by K-21** [comment]
@ashutosh-rath02 can you please assign me under GGSOC'24

**Comment by ashutosh-rath02** [comment]
@K-21 do you have any backgrounds to preview for now?

**Comment by K-21** [comment]
@ashutosh-rath02  ya sure
![b1](https://github.com/ashutosh-rath02/git-re/assets/84450912/d35c943d-755e-4a3f-8f13-9df7d1793d27)
![b2](https://github.com/ashutosh-rath02/git-re/assets/84450912/c6485a70-3c9d-42a9-b71e-b0cbc6d335bb)
this are few samples which  i think would look good but if you have something specific please let me know so that i can work accordingly

**Comment by ashutosh-rath02** [comment]
No these are very messy, try some modern simple backgrounds more sort of grids and dots kind of

**Comment by Tejsvapandey1** [comment]
can i work on this i think this kind of background might look good 
![pexels-timmossholder-3612932](https://github.com/ashutosh-rath02/git-re/assets/142985566/5ce07d57-3732-4ab0-b525-a6efb3a41819)

**Comment by ashutosh-rath02** [comment]
No these looks messy too

**Comment by naisargi17** [comment]
https://github.com/ashutosh-rath02/git-re/assets/111778403/a60387de-8b25-4c29-8b6c-25d0ba27e51b

I can do it like this ,also we can add some animation elements like circle and cylinder.
for the same through animation it will look some user friendly and attractive.

kindly ,assign me under gssoc'24 .

**Comment by ashutosh-rath02** [comment]
@naisargi17 Can you make this happen?
https://ui.aceternity.com/components/hero-highlight

**Comment by naisargi17** [comment]
> @naisargi17 Can you make this happen? https://ui.aceternity.com/components/hero-highlight

yes I can do it .

**Comment by ashutosh-rath02** [comment]
@naisargi17 here you go

**Comment by naisargi17** [comment]
Do you want the hightlight part also ?

https://github.com/ashutosh-rath02/git-re/assets/111778403/3567828b-9110-4ed4-bad8-a25aa6311a35

**Comment by RamakrushnaBiswal** [comment]
hi @ashutosh-rath02 sir the background is not redesigned till now can you assign it to me , i can do it with one day

**Comment by purn1ma** [comment]
hey @ashutosh-rath02  i have solved this issue. you can suggest me some changes if you want.  Can you please assign this issue to me?

![Screenshot 1946-03-29 at 9 03 01 PM](https://github.com/ashutosh-rath02/git-re/assets/81813819/9ba3e292-7cda-4dbf-bc46-03df0348d926)
![Screenshot 1946-03-29 at 9 02 48 PM](https://github.com/ashutosh-rath02/git-re/assets/81813819/f5cc7adc-5307-4e63-ba4f-1e80013bbdd1)
![Screenshot 1946-03-29 at 9 02 31 PM](https://github.com/ashutosh-rath02/git-re/assets/81813819/4319d44d-3d68-43d5-8c71-9ef3e4b79798)
![Screenshot 1946-03-29 at 9 01 39 PM](https://github.com/ashutosh-rath02/git-re/assets/81813819/7b418175-b449-4221-99d7-e866bc30be65)

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #123 has been closed. Thank you for your contribution!
