### ISSUE TITLE
Light effect on logo git-re main

### ISSUE THREAD

**Issue by Chelseasingla1** [ashutosh-rath02/git-re#125]
**Is your feature request related to a problem? Please describe.**
For ui and making website more interactive

**Describe the solution you'd like**
I would like to add a light effect on main git-re 

**Describe alternatives you've considered**

**Additional context**
Here:
![image](https://github.com/ashutosh-rath02/git-re/assets/129886894/39cdd9d4-680d-410c-9681-bb979e27896c)

What problem is this feature trying to solve?

How do we know when the feature is complete?

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn: chelsea-singla-57ab092a0
<br>GitHub: Chelseasingla1
<br>Discord: sia2475
<br>Twitter: CSingla43252

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by Chelseasingla1** [comment]
Please assign me this issue under GSSoC'24.

**Comment by ashutosh-rath02** [comment]
Can you elaborate what is light effect?

**Comment by Chelseasingla1** [comment]
> Can you elaborate what is light effect?

Like when we hover over it, the text be showing some effects

**Comment by ashutosh-rath02** [comment]
I would love to see the effect you propose😊

**Comment by Chelseasingla1** [comment]
> I would love to see the effect you propose😊

Okay sure

**Comment by ashutosh-rath02** [comment]
Hey @Chelseasingla1 ,you can check out discussion for a new feature discussion https://github.com/ashutosh-rath02/git-re/discussions/133

**Comment by ashutosh-rath02** [comment]
@Chelseasingla1 any updates?

**Comment by ashutosh-rath02** [comment]
Will close this issue tomorrow if unresponsive😊

**Comment by ashutosh-rath02** [comment]
Hello @Chelseasingla1! Your issue #125 has been closed. Thank you for your contribution!
