### ISSUE TITLE
enhancement: add skeleton loading to recent users cards

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#127]
In the current version, the recent user carousel is rendered when the recent users are fetched. Instead, apply the skeleton loading is better idea which improves the user experience.

Skeleton loading demo: https://skeleton-loading-nextjs.vercel.app/

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Go ahead @dhairyathedev , also add some loading states to the buttons(build resume, logout and generate)
