### ISSUE TITLE
feat: Add a rating system for user on resume

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#128]
**Is your feature request related to a problem? Please describe.**
We need to devise a rating system that can be used to rate the resume. 

**Describe the solution you'd like**
It should be based on contributions, stars, followers, organization activity etc.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
Bring a rating system among the users

How do we know when the feature is complete?

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn:
<br>GitHub:
<br>Discord:
<br>Twitter:

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by ashutosh-rath02** [comment]
This issue is open for discussion

**Comment by ratishjain12** [comment]
@ashutosh-rath02 lets discuss this about factors to add for calculating score of the resume on discord :)

**Comment by abhiperfect** [comment]
### Feature Request: Resume Rating System

#### Problem:
We need a rating system to evaluate resumes based on various factors such as contributions, stars, followers, and organization activity.

#### Solution:
Develop a comprehensive rating system that considers multiple metrics to assess the quality of resumes submitted by users. This system will provide valuable feedback and help users understand the strengths and weaknesses of their resumes.

#### Implementation:
1. **Metric Selection**: Choose relevant metrics such as contributions to open-source projects, stars received on GitHub repositories, number of followers, and activity within organizations.

2. **Rating Algorithm**: Design an algorithm that calculates an overall rating based on weighted averages of individual metrics. Adjust weights based on the importance of each metric.

3. **User Interface**: Integrate the rating system into the resume submission process, displaying the rating alongside each resume. Provide users with detailed insights into how their resumes were rated.

4. **Feedback Mechanism**: Allow users to receive feedback on their resumes, highlighting areas for improvement and suggesting ways to enhance their ratings.

#### Alternatives:
Consider simpler rating systems based on a single metric, such as the number of contributions or stars received. However, a comprehensive rating system that takes multiple factors into account will provide more valuable insights to users.

#### Completion Criteria:
The feature is complete when:
- The rating system is fully implemented and integrated into the resume submission process.
- Users can view their resume ratings and receive detailed feedback.
- The algorithm produces accurate and meaningful ratings based on selected metrics.
- The rating system enhances user engagement and improves the quality of submitted resumes.

**Comment by nishant0708** [comment]
can you assign me this issue under gssoc 24.

**Comment by ashutosh-rath02** [comment]
https://github.com/ashutosh-rath02/git-re/discussions/133

**Comment by ashutosh-rath02** [comment]
@dhairyathedev

**Comment by dhairyathedev** [comment]
Hey @ashutosh-rath02, can you please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #128 has been closed. Thank you for your contribution!
