### ISSUE TITLE
Bug/testimonial link on the navbar is not functioning as expected.

### ISSUE THREAD

**Issue by abhiperfect** [ashutosh-rath02/git-re#137]
**Describe the bug**
The bug is that the link for accessing the bug/testimonial feature on the navbar is unresponsive or not directing users to the intended destination when clicked.

**To Reproduce**

1. Navigate to the website's navbar.
2. Look for the "Bug/Testimonial" link.
3. Click on the "Bug/Testimonial" link.
4. Observe that the link does not lead to the expected destination or fails to respond at all.

**Expected behavior**
The expected behavior is that when clicking on the "Bug/Testimonial" link in the navbar, users are directed to the appropriate section of the website where they can either report a bug or provide a testimonial.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn: <a href="https://www.linkedin.com/in/abhishek-prajapati-841231248/" target="_blank">LinkedIn</a>
<br>GitHub: <a href="https://github.com/abhiperfect" target="_blank">GitHub</a>
<br>Discord: abhi_perfect007
<br>Twitter:  <a href="https://twitter.com/abhi_perfect007" target="_blank">Twitter</a>

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by abhiperfect** [comment]
Would you please assign me this issue.

**Comment by ashutosh-rath02** [comment]
Resolved
