### ISSUE TITLE
[Critical BUG]: Server side error in resume page

### ISSUE THREAD

**Issue by rohansen856** [ashutosh-rath02/git-re#140]
**Describe the bug**
The Website gives critical error `Application error: a client-side exception has occurred (see the browser console for more information).`, when generating the resume

**To Reproduce**
1. Login
2. Enter your githuub username
3. Press `Generate`
4. Error in page `https://git-re.vercel.app/resume/<your-github-username>`

**Expected behavior**
The user should see his built resume on the page and client error should not occur.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn: https://www.linkedin.com/in/rohan856/
<br>GitHub: https://github.com/rohansen856
<br>Discord: @rohansen856
<br>Twitter: @rohansen856

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by ashutosh-rath02** [comment]
resolved
