### ISSUE TITLE
[Fix]: Fixed correct alignment for tablet view

### ISSUE THREAD

**Issue by SrinivasDevolper** [ashutosh-rath02/git-re#142]
**Describe the bug**
In the Tablet above (width-768px) and below (width- 1440px) view UI alignment is not as good

**Expected behavior**
I can fix correct alignment behavior for tablet view 

**Screenshots**

Issue is here
![git re issue1](https://github.com/ashutosh-rath02/git-re/assets/121508628/49b716c3-27f1-4056-8108-6b5e71bea9eb)
![git re issue2](https://github.com/ashutosh-rath02/git-re/assets/121508628/cd5dad4e-21af-4668-9c80-661ba6c8cb82)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**I am GSSOC24 Contributor**
## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn: https: //www.linkedin.com/in/srinivasdov/
<br>GitHub: https://github.com/SrinivasDevolper
<br>Twitter: https://x.com/DogiparthiOm

If you Follow us in both social medias we provide 'level2'
\*Only First time
I am a new follower to you in what you have pages, I Followed all your pages

**Comment by ashutosh-rath02** [comment]
Go ahead @SrinivasDevolper

**Comment by ashutosh-rath02** [comment]
@SrinivasDevolper updates?

**Comment by Tejsvapandey1** [comment]
SIR CAN YOU ASSIGN ME THIS I WOULD LIKE TO WORK ON THIS

**Comment by ashutosh-rath02** [comment]
Go ahead @Tejsvapandey1

**Comment by ashutosh-rath02** [comment]
Hello @SrinivasDevolper! Your issue #142 has been closed. Thank you for your contribution!
