### ISSUE TITLE
Bug on Show Repositories and show Contributions 

### ISSUE THREAD

**Issue by VSNSRUJANA123** [ashutosh-rath02/git-re#143]
**Describe the bug**
contributions list : In show contributions contains some error show when I increase number in contributor list first it shows correct contributor list then 
decrease the number  it doesn't show proper output 
Repositories : In Repositories list create a number limit just show the recent 5 Repositories display otherwise the number doesn't increase the more

**Expected behavior**
@ashutosh-rath02  Please assign me i will resolve this two issues

**Screenshots**

contributions  bug video : https://github.com/ashutosh-rath02/git-re/assets/127814497/9bcdd0de-33d5-4cd2-8e5d-280141387650
Repositories bug video : https://github.com/ashutosh-rath02/git-re/assets/127814497/a96cc5eb-6718-4c7a-a732-1cb80652ddbb

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn: https://www.linkedin.com/in/srujanadvsn/
<br>GitHub:  https://github.com/VSNSRUJANA123
<br>Twitter:  https://x.com/DvsnSrujana

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by ashutosh-rath02** [comment]
Go ahead @VSNSRUJANA123 all the best

**Comment by ashutosh-rath02** [comment]
@VSNSRUJANA123 updates?

**Comment by atharvarekhawar** [comment]
hey @ashutosh-rath02 , if no one is working on this issue then I would like to contribute to it , plz assign this to me.

I will create PR in one day.

**Comment by atharvarekhawar** [comment]
@ashutosh-rath02 how many max repos the resume can contain, as for now, it is allowing only 6 so do you want to limit it to a specific number or let the user add as many as they want?

**Comment by ashutosh-rath02** [comment]
Yeah limit it to 6 for now

**Comment by ashutosh-rath02** [comment]
@atharvarekhawar see the description of the issue and make a video according to it, to replicate the bugs

**Comment by ashutosh-rath02** [comment]
Hello @VSNSRUJANA123! Your issue #143 has been closed. Thank you for your contribution!
