### ISSUE TITLE
Responsive Navbar Not Shown

### ISSUE THREAD

**Issue by VSNSRUJANA123** [ashutosh-rath02/git-re#144]
**Is your feature request related to a problem? Please describe.**

Responsive navbar doesn't display in mobile devices

![responsive git-re](https://github.com/ashutosh-rath02/git-re/assets/127814497/4ea33463-8def-406b-85cd-fcce3f3636ee)

these two are shown in from tablet and laptop devices but not in mobile device

![responsive git-re1](https://github.com/ashutosh-rath02/git-re/assets/127814497/42df38e6-c9db-4d76-a4b0-0c5b4db03770)

**Describe the solution you'd like**
I will add responsive navbar in mobile device @ashutosh-rath02 Please assign me

**Comment by ashutosh-rath02** [comment]
@VSNSRUJANA123 updates?

**Comment by atharvarekhawar** [comment]
hey @ashutosh-rath02 , if no one is working on the issue then I would like to contribute to it , can you assign me .

**Comment by ashutosh-rath02** [comment]
@atharvarekhawar go ahead

**Comment by ashutosh-rath02** [comment]
Hello @VSNSRUJANA123! Your issue #144 has been closed. Thank you for your contribution!
