### ISSUE TITLE
[Feature]: User Already Existed Text In Recent Users Section

### ISSUE THREAD

**Issue by SrinivasDevolper** [ashutosh-rath02/git-re#145]
**Is your feature request related to a problem? Please describe.**

If the user already generated his name then it should show the warning message **user already existed**

**Describe the solution you'd like**

I can provide **user already existed** text message in generate button section

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

https://github.com/ashutosh-rath02/git-re/assets/121508628/1766b249-2559-4b0a-bfd9-0ddf6298888e

How do we know when the feature is complete?

https://github.com/ashutosh-rath02/git-re/assets/121508628/a1e1fe96-78c1-49dd-b0a0-7d8ba9de710b

**I am GSSOC24 contributor** please assign this issue, I would like to work on that

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn: https://www.linkedin.com/in/srinivasdov/
<br>GitHub: https://github.com/SrinivasDevolper
<br>Twitter: https://x.com/DogiparthiOm

If you Follow us in both social medias we provide 'level2'
\*Only First time
I followed all your social medias

**Comment by supriyabharane** [comment]
I would like to work On this issue please assign it To me

**Comment by ashutosh-rath02** [comment]
We need the resume each time someone generates it, user won't search through recent users and find out his name.
