### ISSUE TITLE
Typo Fix

### ISSUE THREAD

**Issue by PranotiPD** [ashutosh-rath02/git-re#146]
**Describe the bug**
Typo fix

![Screenshot (765)](https://github.com/ashutosh-rath02/git-re/assets/97724414/85c3c225-f74b-4860-b0a5-927f04af7adc)

u should be small in Users.

**Comment by ashutosh-rath02** [comment]
Go ahead @PranotiPD

**Comment by ashutosh-rath02** [comment]
Hello @PranotiPD! Your issue #146 has been closed. Thank you for your contribution!

**Comment by ashutosh-rath02** [comment]
Minor issue
