### ISSUE TITLE
Bug:  404 Error on Canceling GitHub Login for Build Resume Feature

### ISSUE THREAD

**Issue by Aniket-2504** [ashutosh-rath02/git-re#148]
Hello @ashutosh-rath02,

Your project was amazing bro, I followed you on social platforms

## Here is the Issue -  

The "Build Resume" feature on the website. When users click on "Build Resume," they are redirected to the GitHub login page. However, if the login process is canceled, it results in a 404 error page.

## Screenshot -
To help illustrate the issue, I have attached a screenshot for your reference.-

https://github.com/ashutosh-rath02/git-re/assets/145179532/ea4d5c62-3a48-42a7-8f49-646ec61cd83b

Could you please assign this task to me? i want to fix this issue 

I look forward to your response.

**Comment by ashutosh-rath02** [comment]
Go ahead @Aniket-2504 , all the best

**Comment by ashutosh-rath02** [comment]
@Aniket-2504 updates?

**Comment by Aniket-2504** [comment]
I'm working on the issue but need a bit more time to resolve some challenges. I'll update you soon.

**Comment by dhairyathedev** [comment]
Hi @ashutosh-rath02,

If the author is unable to resolve this issue, please feel free to assign it to me. I've already resolved this issue locally and would be happy to help out.

https://github.com/ashutosh-rath02/git-re/assets/65452005/380e666a-4bd0-43df-a2a0-38d23d1bcaf3

**Comment by Aniket-2504** [comment]
Just give me few hours I'll also working on the issue

**Comment by Aniket-2504** [comment]
Hello @dhairyathedev you can proceed with the issue bro

**Comment by dhairyathedev** [comment]
Hey @ashutosh-rath02, you can assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Hello @Aniket-2504! Your issue #148 has been closed. Thank you for your contribution!
