### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [ashutosh-rath02/git-re#153]
### Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/ashutosh-rath02/git-re/assets/73957207/f778b04f-243c-428b-bcd2-d21ca365a113)

- and the issue templates will look like this:

![image](https://github.com/ashutosh-rath02/git-re/assets/73957207/9e8185b9-b53e-4035-85f6-881a8b2bea3a)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by ashutosh-rath02** [comment]
Go ahead @TonyStark-47 all the best

**Comment by TonyStark-47** [comment]
Hey @ashutosh-rath02, I have raised a PR #164 related to this issue. Please check it out.

**Comment by ashutosh-rath02** [comment]
Hello @TonyStark-47! Your issue #153 has been closed. Thank you for your contribution!
