### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [ashutosh-rath02/git-re#155]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by ashutosh-rath02** [comment]
Go ahead @suhanipaliwal , please provide me some examples beforehand

**Comment by ashutosh-rath02** [comment]
Hello @suhanipaliwal! Your issue #155 has been closed. Thank you for your contribution!
