### ISSUE TITLE
bug: error occurs when viewing the resume of a profile

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#157]
**Describe the bug**
When viewing a resume of a user who haven't added website url or blog uurl to their github profile. Then their profile is not viewable and error page renders.

To solve this we need to add proper validation to rendering and type checking.

**To Reproduce**

Few accounts:
https://git-re.vercel.app/resume/ANI2707
https://git-re.vercel.app/resume/Debatreya

**Screenshots**
<img width="1679" alt="Screenshot 2024-05-22 at 10 46 05 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/d70cc9f9-9c59-4dc8-8cdc-cde03437dbbd">

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
If you have a PR ready fire it away @dhairyathedev
