### ISSUE TITLE
[Feat]: Auto Commenting Feat for Issue Creation

### ISSUE THREAD

**Issue by Asymtode712** [ashutosh-rath02/git-re#159]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem. When issues are created in a project, it is important to provide immediate acknowledgment and guidance to the issue creator. However, manually commenting on every newly created issue can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling ignored or discouraged from further participation.

**Describe the solution you'd like**
I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This comment could include acknowledgment of the issue, guidelines for further steps, or any other relevant information. The automation should be customizable to accommodate different project workflows and communication styles.

**What problem is this feature trying to solve?**
This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

![issue creation](https://github.com/ashutosh-rath02/git-re/assets/115717746/e5633518-464a-48a5-ae3f-c72aa942ab38)

## Task

- [X] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [X]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn: https://linkedin.com/in/siddheya-kulkarni
<br>GitHub: https://github.com/Asymtode712
<br>Discord:
<br>Twitter: https://x.com/sidkulkarni712

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by Asymtode712** [comment]
@ashutosh-rath02 As the current workflow only works for first interaction, using the proposed workflow a comment will be added on each created issue

**Comment by Asymtode712** [comment]
@ashutosh-rath02 please assign me this issue

**Comment by ashutosh-rath02** [comment]
Go ahead @Asymtode712 , all the best
