### ISSUE TITLE
[Feat]: Workflow for closing Old PRs 

### ISSUE THREAD

**Issue by Asymtode712** [ashutosh-rath02/git-re#161]
**Is your feature request related to a problem? Please describe.**
Over time, open pull requests (PRs) can accumulate in a repository, cluttering the interface and making it difficult to focus on active development tasks. Additionally, outdated or abandoned PRs may no longer serve their intended purpose and should be closed to maintain repository cleanliness.

**Describe the solution you'd like**
Implement a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.

**What problem is this feature trying to solve?**
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

![Close Old PRs](https://github.com/ashutosh-rath02/git-re/assets/115717746/ec1b2c8d-c637-456f-902f-ac445338c63b)

**Comment by Asymtode712** [comment]
@ashutosh-rath02 please assign me this issue

**Comment by ashutosh-rath02** [comment]
Instead create a workflow that merges PRs on commenting like /rtm to merge the ready PR after evaluation

**Comment by Asymtode712** [comment]
@ashutosh-rath02 Yeah it's a good feature, but this issue is about closing old uninteracted PRs

**Comment by ashutosh-rath02** [comment]
I would like to have that with me for closing old PRs😊

**Comment by ashutosh-rath02** [comment]
Hello @Asymtode712! Your issue #161 has been closed. Thank you for your contribution!
