### ISSUE TITLE
[Feat]: Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [ashutosh-rath02/git-re#163]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem. When contributors raise pull requests (PRs) in a project, it is crucial to provide immediate acknowledgment and feedback to encourage collaboration and maintain transparency. However, manually commenting on every PR can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling undervalued or discouraged from further participation.

**Describe the solution you'd like**
This solution introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.

**What problem is this feature trying to solve?**
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

![PR raised](https://github.com/ashutosh-rath02/git-re/assets/115717746/f7368cd3-3068-411b-93c2-2b0c25e07494)

**Comment by ashutosh-rath02** [comment]
Go ahead @Asymtode712

**Comment by Asymtode712** [comment]
@ashutosh-rath02 All the PRs have been raised, just to ensure smooth working of all workflows just follow these below steps:

**Step 1: Create a Personal Access Token (PAT) with repo Permission**


**1. Navigate to Settings:**

 - Click on your profile picture in the upper-right corner of the page.
 - Select "Settings" from the dropdown menu.

**2. Go to Developer Settings:**

- In the left sidebar, scroll down and click on "Developer settings."

**3. Create a New Token:**

- Click on "Personal access tokens -> Token (classic)" in the left sidebar.
- Click on the "Generate new token" button.

**4. Configure the Token:**

- Token Description: Enter a descriptive name for the token (e.g., Repo Access Token).
- Expiration: Set no expiration.
- Select Scopes: Check the box next to repo to grant full control of private repositories.

**5. Generate Token:**

- Scroll down and click on the "Generate token" button.
- Important: Copy the token to a secure location. You will not be able to see it again once you navigate away from the page.
<br>

**Step 2: Assign the Token to GITHUB_TOKEN Environment Variable**

**1. Navigate to Your Repository:**

- Go to your repository on GitHub.
- Click on the "Settings" tab.

**2. Go to Secrets:**

- In the left sidebar, click on "Secrets and variables" and then "Actions".

**3. Create a New Secret:**

- Click on the "New repository secret" button.
- Name: Enter GITHUB_TOKEN.
- Value: Paste your generated token.
- Click on the "Add secret" button.

**Comment by ashutosh-rath02** [comment]
Secret names must not start with GITHUB_

**Comment by ashutosh-rath02** [comment]
change it to this everywhere MY_SECRET_TOKEN

**Comment by ashutosh-rath02** [comment]
Hello @Asymtode712! Your issue #163 has been closed. Thank you for your contribution!
