### ISSUE TITLE
enhancement: match product hunt widget theme for dark/light mode

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#170]
### Issue
Currently the product hunt widget is static and doesn't match with the light/dark mode theme of the page.

### Screenshots:

**Light Mode**:

![image](https://github.com/ashutosh-rath02/git-re/assets/65452005/715e490a-f256-44f5-8a11-d05d678316a5)

**Dark Mode**:

![image](https://github.com/ashutosh-rath02/git-re/assets/65452005/de032ebf-ee6e-432b-9ce5-375bca6010ff)

Please assign this issue to me

**Comment by ashutosh-rath02** [comment]
Let it be for now @dhairyathedev . Producthunt has it's own color so be it.😊 You can look up for some new features as you have contributed pretty much to this project

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #170 has been closed. Thank you for your contribution!

**Comment by dhairyathedev** [comment]
> Let it be for now @dhairyathedev . Producthunt has it's own color so be it.😊 You can look up for some new features as you have contributed pretty much to this project

No problem, @ashutosh-rath02. Just so you know, I was using the official Product Hunt light mode widget..
