### ISSUE TITLE
[ FEAT ] : Feature to copy sharable resume link to clipboard

### ISSUE THREAD

**Issue by kshavp** [ashutosh-rath02/git-re#176]
**Is your feature request related to a problem? Please describe.**
Fortunately, we have the options to share the generated resume on X (Twitter), Whatsapp and Linkedin. Additionally, we can give a **Copy Sharable Link** feature in the _Share your resume_ section when we try to share.

**Describe the solution you'd like**
The approach would be to just store the current URL to the clipboard and that's it.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
There are too much social media applications where we can share the resume, thus a sharable link to the clipboard would solve this issue.

How do we know when the feature is complete?
I'll raise a PR when it's done.

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn:
<br>GitHub: https://github.com/kshavp
<br>Discord: keshavp
<br>Twitter: https://x.com/keshavpriyam

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by kshavp** [comment]
Hey @ashutosh-rath02 , the functionality is almost done, need a quick suggestion on showing feedback to the user that the link is copied. 

We can have a toast as well as a notification popover as shown in the media.

![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/cc105bb3-8146-4ed6-b243-cfef2be404d5)

**Comment by ashutosh-rath02** [comment]
Ya anything works it just needs to notify the user, a green tick in place of copy sign would even do
