### ISSUE TITLE
[ FEAT ] : Export the Resume as PDF

### ISSUE THREAD

**Issue by kshavp** [ashutosh-rath02/git-re#177]
**Is your feature request related to a problem? Please describe.**
We can have an option to download or export the generated resume as a pdf file.

**Describe the solution you'd like**
Possibly we would use jspdf library in this feature, but I'll update if i find a better alternative that I'd use before making a PR.

**Describe alternatives you've considered**
Will Update.

What problem is this feature trying to solve?
We can enable the functionality to store the resume as a pdf.

How do we know when the feature is complete?
I'll Raise the PR

## Task

- [x] Follow Us On social media - <a href="https://www.linkedin.com/in/rathashutosh/" target="_blank">LinkedIn</a> <a href="https://twitter.com/v_ashu_dev" target="_blank">Twitter</a>
      Let's connect
- [x]      <a href="https://github.com/ashutosh-rath02" target="_blank">GitHub</a>

## Enter you User Id's:

LinkedIn:
<br>GitHub: https://github.com/kshavp
<br>Discord: keshavp
<br>Twitter: https://x.com/keshavpriyam

If you Follow us in both social medias we provide 'level2'
\*Only First time

**Comment by ashutosh-rath02** [comment]
@kshavp #138 You can check this out here. Try downloading the resume once, you will see some disorientation in the text. If you can try to improve it you can work on it. Closing this as duplicate

**Comment by ashutosh-rath02** [comment]
Hello @kshavp! Your issue #177 has been closed. Thank you for your contribution!

**Comment by kshavp** [comment]
@ashutosh-rath02 Sure, alright.
