### ISSUE TITLE
[Documentation Update]: Add npm run build and npm run start instructions to contributing.md

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The current contributing.md file does not mention that contributors should run `npm run build` and subsequently `npm run start` to prevent errors during the deployment process. This omission can lead to issues that could be avoided with proper instructions.

### Suggested Change

Update the contributing.md file to include a section that instructs contributors to run `npm run build` and `npm run start` before submitting their pull requests. This will ensure that they catch any build-related errors early in the development process.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #182 has been closed. Thank you for your contribution!
