### ISSUE TITLE
Feature: Adding a home button in the navbar

### ISSUE THREAD

**Issue by Annu117** [ashutosh-rath02/git-re#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Most websites have a home button to redirect to the home screen. They will not guess on clicking the logo; it will return to the home screen. 

### Use Case

It will reduce guesswork about where the users can return back. 

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/108427028/4d8174e3-47a3-460f-a70a-cd5f88a1c9e1)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead @Annu117 and make it for smaller screens. Do provide screenshots

**Comment by Sid-80** [comment]
@ashutosh-rath02 I am willing to work on this issue

**Comment by ashutosh-rath02** [comment]
Hello @Annu117! Your issue #183 has been closed. Thank you for your contribution!
