### ISSUE TITLE
📝[Docs]: add rating system docs

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#185]
Currently, there is no documentation explaining how the resume rating system works. To address this, I will create and add a detailed document outlining the rating system's mechanics. 

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #185 has been closed. Thank you for your contribution!
