### ISSUE TITLE
[Feature Request]: Creating a custom cursor 

### ISSUE THREAD

**Issue by YadlaMani** [ashutosh-rath02/git-re#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a custom cursor to the website

### Use Case

It would make the website more appealing and cool

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Can you produce some example?

**Comment by ashutosh-rath02** [comment]
I don't think these matches our project themes. We have a pretty clean UI and let it be so😊

**Comment by ashutosh-rath02** [comment]
If you can show so

**Comment by ashutosh-rath02** [comment]
Hello @YadlaMani! Your issue #187 has been closed. Thank you for your contribution!
