### ISSUE TITLE
refactor: Transition Landing Page from Server-Side to Client-Side Rendering

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#188]
### Issue
The current landing page is server-rendered, leading to longer load times, poor user experience, and a lower performance score. As the homepage page is most viewed page on the website, server-side rendering can be expensive and consume Vercel's serverless function quota. To address these issues, we need to transition the landing page to client-side rendering.

### Required Changes
- Refactor authentication validation
- Refactor data fetching

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #188 has been closed. Thank you for your contribution!
