### ISSUE TITLE
[Feature Request]:  Adding animation

### ISSUE THREAD

**Issue by harshmishra19** [ashutosh-rath02/git-re#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Your landing page already looks fantastic, but incorporating a 3d image with animation could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.
If you could assign me this task under GSSOC24, I would be thrilled to work on it.

### Use Case

This upgrade in your page will make your website look more appealing

### Add ScreenShots

![git](https://github.com/ashutosh-rath02/git-re/assets/115486960/2a0bc689-da33-425c-8643-55fb678be49c)

ON THIS PAGE I WANT TO ADD THIS

![vite](https://github.com/ashutosh-rath02/git-re/assets/115486960/a9ffb5ac-b074-4fe5-8373-64effcf93c18)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Ok this can be done make something slick and add. Also look for some matching background

**Comment by harshmishra19** [comment]
Yess on it

**Comment by ashutosh-rath02** [comment]
@harshmishra19 updates?

**Comment by harshmishra19** [comment]
Working on that logo

**Comment by harshmishra19** [comment]
@ashutosh-rath02 
Do you like it
![gitfinal](https://github.com/ashutosh-rath02/git-re/assets/115486960/1c64586a-7fc2-4e7c-8339-1f1d3f713f24)

**Comment by ashutosh-rath02** [comment]
Hello @harshmishra19! Your issue #190 has been closed. Thank you for your contribution!
