### ISSUE TITLE
Refactor: Remove Redundant Tailwind Config File and Migrate Existing Config to TypeScript

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#191]
### Issue

There are currently two Tailwind CSS configuration files in the project, but one of them is redundant. To resolve this, we need to remove the unnecessary `tailwind.config.ts` file. Additionally, since the application uses TypeScript, we should migrate the working `tailwind.config.js` file to TypeScript.

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #191 has been closed. Thank you for your contribution!
