### ISSUE TITLE
[Feature Request]:   Add hover effects in navbar , footer.

### ISSUE THREAD

**Issue by prachita0504** [ashutosh-rath02/git-re#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

by adding hover effect the web looks more great and user friendly.

### Use Case

in navbar, footer.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Tejsvapandey1** [comment]
@ashutosh-rath02 Hello sir can you assign me this issue and assign me under gssoc

**Comment by ashutosh-rath02** [comment]
Hello @prachita0504! Your issue #199 has been closed. Thank you for your contribution!
