### ISSUE TITLE
[Feature Request]: Addding Hero section Text animation

### ISSUE THREAD

**Issue by Rohitha-pudu** [ashutosh-rath02/git-re#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current one looks great but Adding animation improves the ux

### Use Case

by adding a text animation 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
What type of animations can you please provide some examples?

**Comment by Rohitha-pudu** [comment]
> What type of animations can you please provide some examples?

Type writer effect / text generate effect /flip word effect

**Comment by Shahbaz898414** [comment]
assign me this issue plz

**Comment by ashutosh-rath02** [comment]
Hello @Rohitha-pudu! Your issue #203 has been closed. Thank you for your contribution!
