### ISSUE TITLE
[Feature Request]: Adding button animation 

### ISSUE THREAD

**Issue by Rohitha-pudu** [ashutosh-rath02/git-re#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

By adding some effect /animation to button like moving border animation

### Use Case

it enhances User experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Do provide examples blank issues of animation doesn't make sense

**Comment by Rohitha-pudu** [comment]
> Do provide examples blank issues of animation doesn't make sense

![image](https://github.com/ashutosh-rath02/git-re/assets/116823590/f407bc0f-0ffe-4562-ba0e-6da403dc6204)
moving border

**Comment by ashutosh-rath02** [comment]
Yeah it will look good, go ahead

**Comment by ashutosh-rath02** [comment]
Hello @Rohitha-pudu! Your issue #204 has been closed. Thank you for your contribution!
