### ISSUE TITLE
[Bug]: The footer is not mobile repsonsive

### ISSUE THREAD

**Issue by Rohitha-pudu** [ashutosh-rath02/git-re#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in the mobile the footer elements are aligned to one edge

### Expected behavior

make it responsive by aligning them

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
It is

**Comment by ashutosh-rath02** [comment]
Hello @Rohitha-pudu! Your issue #205 has been closed. Thank you for your contribution!
