### ISSUE TITLE
[Feature Request]: Add Testimonials

### ISSUE THREAD

**Issue by aasthakourav20** [ashutosh-rath02/git-re#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding testimonials like Happy Customers , Client Stories, Rate reviews can be added . 

### Use Case

Adding testimonials will make the project more descriptive &  attract users 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
We already have a What our users say section.

**Comment by ashutosh-rath02** [comment]
Hello @aasthakourav20! Your issue #212 has been closed. Thank you for your contribution!

**Comment by aasthakourav20** [comment]
> Hello @aasthakourav20! Your issue #212 has been closed. Thank you for your contribution!

But one problem is there when we click on Testimonials on Navbar,  nothing changes like it looks unclickable . It seems like the Testimonials aren't linked to any of the pages .
