### ISSUE TITLE
[Bug]: The landing page is having the button product hunt looking uneven

### ISSUE THREAD

**Issue by Latish705** [ashutosh-rath02/git-re#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you see the build resume button wrt to product hunt button it is looking uneven that effect ux

### Expected behavior

the both should have the same height

### Add ScreenShots

<img width="1680" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/104522651/7e5a689d-ec55-4f9d-bac2-1eec42905b92">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Yeah looks like a bug. Go ahead @Latish705

**Comment by Latish705** [comment]
@ashutosh-rath02 
<img width="1680" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/104522651/ff5f3aeb-43ba-47ea-8188-0022e1d6fe7b">
this how if try to make the same size of product hunt button

**Comment by Latish705** [comment]
should I raise the pr?

**Comment by ashutosh-rath02** [comment]
Yeah

**Comment by ashutosh-rath02** [comment]
Hello @Latish705! Your issue #213 has been closed. Thank you for your contribution!
