### ISSUE TITLE
[Feature]:  Smooth Scroll using Lenis

### ISSUE THREAD

**Issue by TenzDelek** [ashutosh-rath02/git-re#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

creating a smooth scroll for better user experience

### Use Case

better user experience

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead but first search through the package.json if any existing package can be used.

**Comment by ashutosh-rath02** [comment]
Hello @TenzDelek! Your issue #214 has been closed. Thank you for your contribution!
