### ISSUE TITLE
hover effect of navbar in dark mode

### ISSUE THREAD

**Issue by dhairyagothi** [ashutosh-rath02/git-re#215]
hello i can add hover effect to navbar items opensource and testimonials in dark mode . assign this to me with label gssoc

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Thanks for the suggestion but it looks good enough

**Comment by ashutosh-rath02** [comment]
Hello @dhairyagothi! Your issue #215 has been closed. Thank you for your contribution!
