### ISSUE TITLE
[Feature Request]: Display with the default template initially and give user option to change

### ISSUE THREAD

**Issue by Rohitha-pudu** [ashutosh-rath02/git-re#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Displaying with the default template initially and give user option to change the templates

### Use Case

user can change templates

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by shreyaspathak11** [comment]
can you assign this to me
??

**Comment by ashutosh-rath02** [comment]
Hey @shreyaspathak11 can you explain your understanding of the issue?

**Comment by ashutosh-rath02** [comment]
Hello @Rohitha-pudu! Your issue #217 has been closed. Thank you for your contribution!
