### ISSUE TITLE
[Bug]: Testimonial link not working

### ISSUE THREAD

**Issue by aryansharma220** [ashutosh-rath02/git-re#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On Clicking on the testimonial link, nothing happens.

### Expected behavior

It should redirect to the testimonial page/section

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/133234867/e89364f7-28a0-4c57-9277-876d719dd18b)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Remove the Opensource and add a home button and correct the redirect of testimonials in smooth scroll

**Comment by ashutosh-rath02** [comment]
Hello @aryansharma220! Your issue #218 has been closed. Thank you for your contribution!
