### ISSUE TITLE
Adding auto scroll to top button

### ISSUE THREAD

**Issue by sharmi4590** [ashutosh-rath02/git-re#223]
User experience enhances when there is less scrolling in the web pages , thus when the user scrolls down to visit the website it will not required to the user to again go back to the top by scrolling as it is a waste of time. Thus adding scroll to top button will take the user to the top in a click.
![stt](https://github.com/ashutosh-rath02/git-re/assets/102676949/4b394748-020b-4b77-9416-74530c9777c9)

This is my previous work
![Screenshot (495)](https://github.com/ashutosh-rath02/git-re/assets/102676949/78125099-0519-4753-925c-f0b305078763)

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
We do not have many sections so this section is not needed for now.

**Comment by ashutosh-rath02** [comment]
Hello @sharmi4590! Your issue #223 has been closed. Thank you for your contribution!
