### ISSUE TITLE
Missing a section in navbar.

### ISSUE THREAD

**Issue by sharmi4590** [ashutosh-rath02/git-re#224]
The navbar for smaller dimensions has the open source section but the navbar in larger dimensions is missing this.
![Screenshot (524)](https://github.com/ashutosh-rath02/git-re/assets/102676949/99c8d2e2-29de-4679-ae86-4282993eb076)
![Screenshot (525)](https://github.com/ashutosh-rath02/git-re/assets/102676949/0d4b5878-9ee7-4c16-8f92-d6db196429f1)

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
You can remove it

**Comment by ashutosh-rath02** [comment]
Hello @sharmi4590! Your issue #224 has been closed. Thank you for your contribution!
