### ISSUE TITLE
[Bug]: Add hover color and text in footor

### ISSUE THREAD

**Issue by AkhilaSunesh** [ashutosh-rath02/git-re#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/ashutosh-rath02/git-re/assets/140897461/f6451f1b-3700-4bdb-9337-ba0bf014ad01)
Add hover color on Contribute and Vote on Product hunt links
Add hover text on social media icons

### Expected behavior

More professional outlook

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
GO ahead @AkhilaSunesh

**Comment by ashutosh-rath02** [comment]
Hello @AkhilaSunesh! Your issue #228 has been closed. Thank you for your contribution!
