### ISSUE TITLE
[Feature Request]: Scroll Back to Top Button

### ISSUE THREAD

**Issue by DishaSethi** [ashutosh-rath02/git-re#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding scroll back to top button .
![Screenshot (627)](https://github.com/ashutosh-rath02/git-re/assets/142926792/22440d68-fa7c-431d-a3ac-a30a3c5bd3bf)
Like here it is given in this website as well. 

### Use Case

It helps the user to smoothly transition back to the top section of the website without much hassle to scroll too much using the scroll bar.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Not required as of now😊

**Comment by ashutosh-rath02** [comment]
Hello @DishaSethi! Your issue #235 has been closed. Thank you for your contribution!
