### ISSUE TITLE
[Feat] : Custom Scrollbar

### ISSUE THREAD

**Issue by TenzDelek** [ashutosh-rath02/git-re#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Converting the default scrollbar to an custom one which align with the theme

### Use Case

improved the visual representation

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead @TenzDelek

**Comment by ashutosh-rath02** [comment]
Hello @TenzDelek! Your issue #236 has been closed. Thank you for your contribution!
