### ISSUE TITLE
[feat]: save the user rating in the database

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#238]
### Issue
The current system does not store user ratings in the database.

### Changes to be Made
- I will add functionality to store ratings for new profiles in the database.
- I will implement a mechanism to check if a rating has been updated, and if so, update the rating in the database accordingly.

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #238 has been closed. Thank you for your contribution!
