### ISSUE TITLE
[Feature Request]: Leaderboard Page

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Leaderboard for the resume ratings

### Use Case

Can be used to know how top profiles are created which can be beneficial for the intermediates and beginners profile. Also, motivation for the experts to compete for the top place on the leaderboard.

### Add ScreenShots

<img width="1680" alt="Screenshot 2024-06-04 at 6 42 55 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/de2f6a9d-25cb-41d7-89d5-cc492623f0c1">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #242 has been closed. Thank you for your contribution!
