### ISSUE TITLE
[Feature Request]:  Crown for top three in leaderboard

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To express the gratitude towards the top three resume in leaderboard, we can add the (golden, silver, bronze) crowns in front of their username.

### Use Case

The introduction of crowns (golden, silver, bronze) for the top three users on the leaderboard can boost engagement and motivation among participants.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #248 has been closed. Thank you for your contribution!
