### ISSUE TITLE
Feedback/contact us form

### ISSUE THREAD

**Issue by ananyag309** [ashutosh-rath02/git-re#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to recommend above the social link section their should be a contact us/ feedback form which allows user to have direct interaction with the admin gaining confidence on the site. @ashutosh-rath02 sir i would love to do so, i would suggest to have a minimal but professional pop up form.

### Use Case

1) User- interaction

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ananyag309** [comment]
@ashutosh-rath02 yes sure sir, will be waiting for your response.

**Comment by ashutosh-rath02** [comment]
Duplicate issue

**Comment by ashutosh-rath02** [comment]
Hello @ananyag309! Your issue #249 has been closed. Thank you for your contribution!
