### ISSUE TITLE
feature: Add testimonial section

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#25]
We have few good responses from our beloved users at ProductHunt and also we can collect from our users through a section in the website.

- [ ] Add a section to collect reviews
- [ ] Add testimonials section. Use acternity ui for the component

**Comment by Anayverma** [comment]
hey @ashutosh-rath02 please assign it to me under gssoc24. I want to work on it.

**Comment by ashutosh-rath02** [comment]
Hey @NilanchalaPanda one issue at a time. Please mention which one you would like to work on.

**Comment by NilanchalaPanda** [comment]
Hey @ashutosh-rath02, sure thing. I would first love to work upon some UI part of the website to finish it off quick. And then move upon the PDF Download issue.

**Comment by ashutosh-rath02** [comment]
Sure thing @NilanchalaPanda Assigning you this

**Comment by NilanchalaPanda** [comment]
Thank for the update @ashutosh-rath02, will start working on the issue.

Can you please share which testimonials you want to display on the website?

**Comment by ashutosh-rath02** [comment]
@NilanchalaPanda You can check ProductHunt for some reviews. Have you checked the tasks mentioned? You have to create a section to accept testimonials. How do you plan to do it?

**Comment by NilanchalaPanda** [comment]
We can store the reviews from the user in a JSON file, and then from the application itself we can parse it to display to the users, Sounds good?

I though of this approach because since there is no configuration for server & database as of now.

**Comment by ashutosh-rath02** [comment]
Sure @NilanchalaPanda make new path `config/content/TestimonialData.js` in the root directory and fetch the data from there

**Comment by NilanchalaPanda** [comment]
Okay, works 🙌🏻
Will add to the file in the mentioned directory.

**Comment by ashutosh-rath02** [comment]
Also @NilanchalaPanda include a Name, photograph and testimonial. Use acternity sliding cards as testimonials.
.vasudev this is my github username. You can dm me over here and I will provide you more testimonials

**Comment by NilanchalaPanda** [comment]
Sure, will use Acternity UI for testimonials section.

I didn't understood about the GitHub username part. Can you again comment, which messaging platform are you referring to for Testimonials Data.

**Comment by ashutosh-rath02** [comment]
> Sure, will use Acternity UI for testimonials section.
> 
> I didn't understood about the GitHub username part. Can you again comment, which messaging platform are you referring to for Testimonials Data.

Sorry my bad. Discord username

**Comment by NilanchalaPanda** [comment]
Okay, got it 👍🏻

**Comment by ashutosh-rath02** [comment]
> Okay, got it 👍🏻 I have sent a friend request.

Can you tag me once on GSSoC server Ashutosh | PA | Git-re . I didnt receive your friend request.

**Comment by NilanchalaPanda** [comment]
Now you can check, I have sent 🙌🏻

**Comment by ashutosh-rath02** [comment]
@NilanchalaPanda Any update on this?

**Comment by NilanchalaPanda** [comment]
Yes, working on the UI first then accordingly add the data.
