### ISSUE TITLE
[Bug]: Mode Selection should be in navbar

### ISSUE THREAD

**Issue by namandude** [ashutosh-rath02/git-re#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I think the mode selection dark or light should be present in the above side of website , having it in bottom doesnt making sense.
![image](https://github.com/ashutosh-rath02/git-re/assets/118013565/c26a7ef0-9ae3-4a7e-9b0f-965e44184fa4)

### Expected behavior

I will make it appear in the navbar or anywhere which can be easily  discoverable .

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/118013565/8aa7aecb-6b77-4ba0-bd26-a9a55dfea1ec)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Let it be there
