### ISSUE TITLE
[Feature Request]: Add Hover effects of Users Section Cards 

### ISSUE THREAD

**Issue by Surajkushwaha12** [ashutosh-rath02/git-re#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add Hover effects on the Users Section Cards

### Use Case

![image](https://github.com/ashutosh-rath02/git-re/assets/134843134/ef0faf83-2a90-4ab1-bedc-339dca7ad571)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @Surajkushwaha12! Your issue #251 has been closed. Thank you for your contribution!
