### ISSUE TITLE
[Bug]: Ratelimit issue

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When visiting multiple (4 to 5) resumes, we encounter a ratelimit error from GitHub due to unuathenicated API calls.

### Expected behavior

There should be no ratelimit errors for the small number of requests.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dhairyathedev** [comment]
Please assign this issue to me

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #252 has been closed. Thank you for your contribution!
