### ISSUE TITLE
[Bug]: Leader board pagination not properly handle 

### ISSUE THREAD

**Issue by CoderSwarup** [ashutosh-rath02/git-re#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in leaderboard the pagination not handled properly we can get the pagination button multiple times not stop any where

### Expected behavior

Pagination handle properly where the next or previous button show only if data available 

### Add ScreenShots

![Screenshot_2024-06-06-13-52-53-15_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ashutosh-rath02/git-re/assets/128630311/2f5708f4-143a-4577-b43d-d75e05040977)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
@CoderSwarup You want to work on it?

**Comment by CoderSwarup** [comment]
> @CoderSwarup You want to work on it?

yes

**Comment by ashutosh-rath02** [comment]
GO ahead @CoderSwarup

**Comment by CoderSwarup** [comment]
@ashutosh-rath02  why i cant able to get data HERE i completely setup the DB and Redis Also

![image](https://github.com/ashutosh-rath02/git-re/assets/128630311/d5a01f31-9764-496a-876a-00b9e68466ac)



![image](https://github.com/ashutosh-rath02/git-re/assets/128630311/ad1018c0-04f2-434d-aaa0-f31f75fc4e54)

![image](https://github.com/ashutosh-rath02/git-re/assets/128630311/e061ba7d-c7bd-431a-ab35-e8a0fe409484)

**Comment by ashutosh-rath02** [comment]
@CoderSwarup you need to search for some usernames then only they will get stored in your db

**Comment by dhairyathedev** [comment]
@CoderSwarup it is because you have not disabled row level security. Also remove all the dummy data you have added and just follow as @ashutosh-rath02 mentioned.

<img width="1180" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/ac194c61-f1b3-4550-accc-5eb05a139b31">

**Comment by CoderSwarup** [comment]
> @CoderSwarup it is because you have not disabled row level security. Also remove all the dummy data you have added and just follow as @ashutosh-rath02 mentioned.
> 
> <img alt="image" width="1180" src="https://private-user-images.githubusercontent.com/65452005/337880949-ac194c61-f1b3-4550-accc-5eb05a139b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjM5NTgsIm5iZiI6MTcxNzg2MzY1OCwicGF0aCI6Ii82NTQ1MjAwNS8zMzc4ODA5NDktYWMxOTRjNjEtZjFiMy00NTUwLWFjY2MtNWViMDVhMTM5YjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDE2MjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZDg3YTFlZmRlNWFkOTFlNmVkNDA5NTAxYmFhYjEyZWMwYmMwNDI4YTNhM2RhNGRhOGU1YmYyNTJlOTBhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uKgmwxnQh80EqORi4rc6Oy_NFyM05QTTpcobv-tUXrk">

Thanks 👍

**Comment by CoderSwarup** [comment]
@ashutosh-rath02  i will raise pr within 2 days , sorry for late
