### ISSUE TITLE
[feature]: Redesign the resume page

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#258]
### Issue
The current version of the resume page looks bit old fashioned and unpleasing. It needs to be redesigned.

### Changes required
- New design 
- Graphs
- New APIs for graph data fetching
- Custom Components
- Drawer for the customization

### Screenshots
Initial layout of the new resume desgin
![image](https://github.com/ashutosh-rath02/git-re/assets/65452005/3355d6dd-6643-4caf-9a8b-d02a8e83ec59)

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #258 has been closed. Thank you for your contribution!
