### ISSUE TITLE
refractor: Improve codebase

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#26]
Currently all the fetching of data is done in a single file. Use recent Nextjs methods to structure the code to professional standards.

- [ ] Redefine file structure
- [ ] Refractor codebase to improve optimization

**Comment by Abhinavpatra** [comment]
Hey  @ashutosh-rath02  i will use standard industry practices to structure the files under appropriate folders and edit the code, while making slight adjustments to it, in order to make it more readable. let me know if you can assign it to me under GSSOC'24. Thanks.

**Comment by ashutosh-rath02** [comment]
Sure @Abhinavpatra start working on it.

**Comment by ashutosh-rath02** [comment]
@Abhinavpatra any updates on this?

**Comment by Abhinavpatra** [comment]
I have made edits to the code base specifically but assimilating it into folders is proving a much more elaborate task, i have to list them and sort them individually, which might take quite a bit longer for me, I understand if you might wanna assign it to someone else.

**Comment by ashutosh-rath02** [comment]
>  I have made edits to the code base specifically but assimilating it into folders is proving a much more elaborate task, i have to list them and sort them individually, which might take quite a bit longer for me, I understand if you might wanna assign it to someone else.

If you are working on it, you can continue

**Comment by amanjaiswal7236** [comment]
Can you elaborate this, show that I can work on this, and provide some references to it.

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #26 has been closed. Thank you for your contribution!
