### ISSUE TITLE
[ENHANCEMENT]: enhancing the footer UI and responsiveness

### ISSUE THREAD

**Issue by AMS003010** [ashutosh-rath02/git-re#266]
The footer UI and responsiveness can greatly be enhanced to make the user experience better

## Screenshot
![image](https://github.com/ashutosh-rath02/git-re/assets/111883236/9c431fa8-9ac2-4f06-847c-a5e6cdf0c56a)

## Additional points
@ashutosh-rath02  I am seeking to contribute to your project and would like to be assigned this issue under the Gssoc'24.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by neha-kum** [comment]
Can I work on this ?

**Comment by ashutosh-rath02** [comment]
Hello @AMS003010! Your issue #266 has been closed. Thank you for your contribution!

**Comment by ashutosh-rath02** [comment]
Designs will be changed
