### ISSUE TITLE
enhancement: Improve UI

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#27]
The hero section currently has a simple one page view. 
- [ ] Provide figma mockups to improve the UI
- [ ] Code the selected design

**Comment by Anayverma** [comment]
hey @ashutosh-rath02 please assign it to me under gssoc24. I want to work on it.

**Comment by ashutosh-rath02** [comment]
Hey @Anayverma please provide a mockup regarding what changes you suggest.

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02  I want to work on that, Can u described what other components should be added to the hero section ?

**Comment by ashutosh-rath02** [comment]
@SiddharthaArepalli can you provide some mockups for the changes?

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02  
![Screenshot 2024-05-11 102456](https://github.com/ashutosh-rath02/git-re/assets/140429954/46e760dc-0cc4-473a-870b-a81d109b7253)
Iam planing to this if want any other changes make me know !

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02  if u are okay with this assign me !!

**Comment by ashutosh-rath02** [comment]
It is only for Navbar. I would suggest if you can please make a figma file with the new wireframes and then we can work on it... Make a proper color theme and work on it

**Comment by SiddharthaArepalli** [comment]
yeah I can work on it if u would assign me !

**Comment by ashutosh-rath02** [comment]
Done @SiddharthaArepalli

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02 On it !!

**Comment by ashutosh-rath02** [comment]
@dhairyathedev You can work alongside @SiddharthaArepalli to improve the ui

**Comment by ashutosh-rath02** [comment]
Please provide your figma linked emails so that I can add you to figma

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02  Email : s1ddh4rth4goud@gmail.com

**Comment by dhairyathedev** [comment]
@ashutosh-rath02  Here's my email - hello[at]dhairyashah.dev

**Comment by ashutosh-rath02** [comment]
Check @SiddharthaArepalli @dhairyathedev for the invites on figma

**Comment by dhairyathedev** [comment]
@ashutosh-rath02 I have designed new Navbar and Footer. Please have a look 👇

![landing](https://github.com/ashutosh-rath02/git-re/assets/65452005/4bfbf54e-b41c-4289-ac27-443d8d94a303)

P.S. please add me as assignee to this issue.

**Comment by ashutosh-rath02** [comment]
Hey @dhairyathedev can you do it according to our color theme?

**Comment by dhairyathedev** [comment]
> Hey @dhairyathedev can you do it according to our color theme?

Hey @ashutosh-rath02, Here's the new look based on the current working color pallets used 👇

P.S. please add me as assignee to this issue.

<br />
<img width="1280" alt="Landing Page" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/758af73f-3e10-43d8-9f4e-3c1a4b0e6509">

**Comment by ashutosh-rath02** [comment]
Do you have the dark mode design ready coz our website mostly functions on dark mode

**Comment by dhairyathedev** [comment]
> Do you have the dark mode design ready coz our website mostly functions on dark mode?

Hey @ashutosh-rath02, at the moment, I haven't prepared the dark mode design yet. We can work on that later, once @SiddharthaArepalli enhances the hero section on the landing page.

In my opinion, implementing dark mode might not look as visually appealing on the landing page, given that our primary color scheme lies towards darker tones already. It may not contrast well with a black background.

**Comment by ashutosh-rath02** [comment]
@dhairyathedev you can check the current dark mode and if siddharth isnt working so its your issue completely now

**Comment by dhairyathedev** [comment]
@ashutosh-rath02 Here's the dark mode 👇
<br />
<img width="1280" alt="Landing Page (Dark)" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/e99119d2-43bf-4565-bcd6-5a4358be5cc9">

**Comment by dhairyathedev** [comment]
Hey @ashutosh-rath02 If this design is fine, then I start to code.

**Comment by ashutosh-rath02** [comment]
Go ahead
