### ISSUE TITLE
add more social media logos

### ISSUE THREAD

**Issue by jayanththalla** [ashutosh-rath02/git-re#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer the social media part the Discord logo,Instagram logo are missing 

### Use Case

Hover the social media icons with the different colors 

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/121346142/bb35cbb5-8687-4ee7-aaec-c298e54958eb)

please assign me @pa
please label it under the gssoc

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
We don't have those currently

**Comment by ashutosh-rath02** [comment]
Hello @jayanththalla! Your issue #273 has been closed. Thank you for your contribution!
