### ISSUE TITLE
bug: website url is blank in resume page

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#274]
### Issue 
If the user doesn't have any website added to their GitHub profile, it will be shown blank on the resume page

### Fix
Website link should only be rendered if it's present.

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.
