### ISSUE TITLE
[Feature Request]: Add "Back to Top" Button 

### ISSUE THREAD

**Issue by AsmitaMishra24** [ashutosh-rath02/git-re#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The addition of a "Back to Top" button on the all pages of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

### Use Case

1. Convenience: Quickly returns users to the top of the page with one click.
2. Improved Navigation: Simplifies moving back to the main navigation menu or introductory content.
3. Accessibility: Helps users with mobility issues or those using keyboard navigation.
4. Enhanced User Experience: Reflects attention to user-centric design, increasing satisfaction and retention.

### Benefits

1. Time-Saving: Reduces the time and effort needed to navigate long pages.
2. User-Friendly: Makes the website more intuitive and pleasant to use.
3. Inclusive: Supports diverse user needs, adhering to accessibility standards.

### Add ScreenShots

My previous work:

https://github.com/ashutosh-rath02/git-re/assets/146121869/8e00e36d-9ef4-4a42-9e24-81339394f07f

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Shahbaz898414** [comment]
assign me this project

**Comment by ashutosh-rath02** [comment]
Hello @AsmitaMishra24! Your issue #278 has been closed. Thank you for your contribution!
