### ISSUE TITLE
[Bug]: Need some padding for better ui/ux exsisting user section

### ISSUE THREAD

**Issue by Latish705** [ashutosh-rath02/git-re#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="1440" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/104522651/6c96599e-e367-472e-b247-139ca2936023">
In the above ss as we can see the existing user section need some padding from the sides as it look like it going to out of screen not look good

### Expected behavior

there should be some padding from both the side 

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
@Latish705 Please resolve this by tomorrow or else I will have to unassign you.

**Comment by ashutosh-rath02** [comment]
Hello @Latish705! Your issue #281 has been closed. Thank you for your contribution!
