### ISSUE TITLE
[Bug]: Profile tracking is not scrollable

### ISSUE THREAD

**Issue by Latish705** [ashutosh-rath02/git-re#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The profile tracking section is not scrollalble 

### Expected behavior

The profile tracking should be scrollable

### Add ScreenShots

<img width="1440" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/104522651/2aa660d8-8885-4680-b5f5-f86e98826ecc">

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead @Latish705

**Comment by ashutosh-rath02** [comment]
Hello @Latish705! Your issue #282 has been closed. Thank you for your contribution!

**Comment by Latish705** [comment]
@ashutosh-rath02 
<img width="1440" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/104522651/74e18d83-908d-4c7c-a1cf-ef2e9db64c8a">
the generate button on this page is not working the is done perfectly and if I try to go to page /resume/username directly it is working can you help me with that 
<img width="1440" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/104522651/5fdf1995-ccf6-4a0a-8a77-0c58c3107c1a">
I am seeing error like 
<img width="1440" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/104522651/084bf916-4301-4c85-88dd-ec735b373770">

**Comment by ashutosh-rath02** [comment]
@Latish705 this would happen in you press it too many times at once. Click once at wait for some time

**Comment by ashutosh-rath02** [comment]
@Latish705  Please resolve this by tomorrow or else I will have to unassign you.

**Comment by ashutosh-rath02** [comment]
Hello @Latish705! Your issue #282 has been closed. Thank you for your contribution!
