### ISSUE TITLE
[Feature Request]: Project should have a docker method to run locally

### ISSUE THREAD

**Issue by Latish705** [ashutosh-rath02/git-re#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Project should have a docker method to run locally to develop it will easier for user to setup project locally

### Use Case

it will be easier for user to setup locally

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead but I don't see much requirement here. Can you say how it may help, considering website is pretty simple?

**Comment by Latish705** [comment]
@ashutosh-rath02 it will be easier for you to deploy and for user to setup for development without thinking about what all the dependency they need to install 

I you say I can work on it

**Comment by ashutosh-rath02** [comment]
@Latish705  Please resolve this by tomorrow or else I will have to unassign you.

**Comment by Latish705** [comment]
@ashutosh-rath02 yeah will raise pr till tomorrow night for all the issues assigned to to me I am working on it

**Comment by Latish705** [comment]
@ashutosh-rath02 give me time till tomorrow night

**Comment by ashutosh-rath02** [comment]
Hello @Latish705! Your issue #284 has been closed. Thank you for your contribution!
