### ISSUE TITLE
[Bug]: Responsiveness for Recent User Slides

### ISSUE THREAD

**Issue by kshavp** [ashutosh-rath02/git-re#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just like other devices, the cards for recent users should align with tab or 786px and above devices. 

### Expected behavior

At least one card should fit on the screen at a time thus would make it responsive.

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/99f6a161-80ca-4f1d-997e-82f58bd0ec56)

### On which device are you experiencing this bug?

iPhone

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Can you check the whole website and let me know what all things need fixing? I can give you a level3 for that

**Comment by kshavp** [comment]
Sure, would need a day or two, I'll craft the fixes as well so that the issue and PR are added on the same day.

**Comment by kshavp** [comment]
@ashutosh-rath02 Sharing an update 

*1. Responsiveness* for tab-based devices checked, only the Recent User Slides would undergo a fix.

*2. Dark Mode*: The Hyperlinks are supposed to turn to "text-primary" on hover as they do in Light Mode, but currently not happening in dark mode.*
- This fix is required in both Navbar as well the icons provided in the footer. Sharing you the results after fixes:
![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/c572474a-2a1e-44a6-a960-473cb4765db7)
![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/cd2485ed-a3ec-47dc-919f-9f3da84cc60d)

*3. Light Mode*: The Labels provided in profile tracking are merged with the background in the light mode, they are fixed and can be seen as follows:
![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/847a69fc-4151-4a04-936b-5227315341df)
![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/1c94606a-0bb6-41af-b17e-77d4a608ba16)

*4. Made by Ashutosh Rath*: The name in this phrase in the footer can be made a hyperlink to your portfolio website.

*5. Secondary Links in the Footer*: Links such as "Contribute" and "Vote on Product Hunt" should also get covered with hover effect.

**Suggestions and Features**

1. The Generate button in dark mode on Form.tsx can have its text color white, as it looks better in contrast to the gray color.
![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/ebec023a-a2dd-4102-b447-7a1e43033333)

2. The Graphs generated on the profile tracking option can be given an option to be saved/downloaded as image.

3. Auto Complete feature can be added to the Form.tsx while searching for a github username. NOTE: If we directly fetch usernames from github the increase in number of operations can affect website performance, thus we can have a discussion with other contributors regarding the most optimal approach for this feature.

**Comment by ashutosh-rath02** [comment]
Makes sense go ahead, auto complete is not required.

**Comment by ashutosh-rath02** [comment]
Hello @kshavp! Your issue #285 has been closed. Thank you for your contribution!
