### ISSUE TITLE
[Bug]: Testimonial link on Leaderboard page does not navigate to the Testimonial page

### ISSUE THREAD

**Issue by Shahbaz898414** [ashutosh-rath02/git-re#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the Leaderboard page of the project, clicking the link to the Testimonial page does not navigate to the Testimonial page. This issue prevents users from accessing the Testimonial page through the provided link.

### Expected behavior

After clicking the link to the Testimonial page on the Leaderboard page, the user should be redirected to the Testimonial page.

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/e016f318-e5fe-4d34-9696-963aa29c3a39)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Shahbaz898414** [comment]
can you assign me this issue ?

**Comment by ashutosh-rath02** [comment]
@Shahbaz898414 Please resolve this by tomorrow or else I will have to unassign you.

**Comment by Shahbaz898414** [comment]
![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/a3ceff52-113d-4b2e-81a0-ebae8ad9a98f)

can you guide me to solve this issue?

**Comment by ashutosh-rath02** [comment]
Have you created Supabase account? Have you read the project setup file in README?

**Comment by Shahbaz898414** [comment]
> Have you created Supabase account? Have you read the project setup file in README?

Yes i created the Supabase account

Proof
![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/3cf5acdd-f70d-4e14-9972-676c4ab4c043)


![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/58761efe-4040-4071-a9aa-b4e9e0a19051)


![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/bba7828e-9fbb-4d41-bbe6-4ee38962f15f)

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 

thanks you for your time, i am able to setup the project in my system, i did some silly mistake.

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 done  bro, Plz review

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 i fix the issue plz check

**Comment by ashutosh-rath02** [comment]
Hello @Shahbaz898414! Your issue #287 has been closed. Thank you for your contribution!
