### ISSUE TITLE
[Feature Request]:Add a Review Us/Contact us Page 

### ISSUE THREAD

**Issue by komal-agarwal5** [ashutosh-rath02/git-re#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wish to add a page through which people can send their reviews suggestions or any other information (ui form connected with formspree)

### Use Case

This will help to get a better idea of the interests of the users

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Duplicate

**Comment by ashutosh-rath02** [comment]
Hello @komal-agarwal5! Your issue #288 has been closed. Thank you for your contribution!
