### ISSUE TITLE
[Bug]: No Margin on Top and Bottom of Profile Tracker Page

### ISSUE THREAD

**Issue by Shahbaz898414** [ashutosh-rath02/git-re#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no margin at the top and bottom of the Profile Tracker page, causing the elements to be too close to the edges. This makes the page look cluttered and affects the overall readability and aesthetics.

### Expected behavior

There should be a margin at the top and bottom of the page to provide some spacing and improve the layout.

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/80ce889c-7521-4af4-9d73-8032d875e087)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 
can you assign me this issue?

**Comment by ashutosh-rath02** [comment]
@Shahbaz898414 Please resolve this by tomorrow or else I will have to unassign you.

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 , i am getting problem to setup in my system

**Comment by ashutosh-rath02** [comment]
Have read the Readme file it has all informations for the setup?

**Comment by ashutosh-rath02** [comment]
Ok

**Comment by Shahbaz898414** [comment]
Hi @ashutosh-rath02 , then click on Build Resume Button

![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/eb9a7d79-f388-493c-8c97-e85cc9999c3d)

then i got this
![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/9d7149c8-f9b5-4270-b801-0d76399fa303)

**Comment by ashutosh-rath02** [comment]
It's working fine I checked

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 

i try some other method to fix this issue.

**Comment by ashutosh-rath02** [comment]
Any updates @Shahbaz898414 ?

**Comment by Shahbaz898414** [comment]
I will complete by tomorrow.

**Comment by ashutosh-rath02** [comment]
Hello @Shahbaz898414! Your issue #289 has been closed. Thank you for your contribution!
