### ISSUE TITLE
[Feature Request]: Make testimonials card responsive 

### ISSUE THREAD

**Issue by komal-agarwal5** [ashutosh-rath02/git-re#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The testimonials cards isn't responsive 
It looks like this
![IMG_20240615_002550](https://github.com/ashutosh-rath02/git-re/assets/122633300/0f5d25d4-28b2-44a6-8240-d19059335dc1)

I wish to make the sizing something like this,it's a sample 
![IMG_20240610_165731](https://github.com/ashutosh-rath02/git-re/assets/122633300/3a379fd6-34da-4e65-841a-7023e4826e19)

### Use Case

Responsiveness 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
You can reduce the cards size a little for smaller screens, don't change anything else, attach video after raising PR

**Comment by ashutosh-rath02** [comment]
@komal-agarwal5  Please resolve this by tomorrow or else I will have to unassign you.

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 Please resolve this by tomorrow or else I will have to unassign you.

Extremely sorry for the delay due to semester exams,please give me time till tomorrow EOD,I shall complete it

**Comment by ashutosh-rath02** [comment]
Hello @komal-agarwal5! Your issue #290 has been closed. Thank you for your contribution!
