### ISSUE TITLE
[Bug]: Make Graph Points responsive

### ISSUE THREAD

**Issue by Shahbaz898414** [ashutosh-rath02/git-re#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 On mobile devices, the index labels on the graph (Hours of the Day) are too close to each other, making it difficult to read the data properly. The labels should have appropriate margins to improve readability.

### Expected behavior

The graph labels should have appropriate margins on mobile devices to ensure that the data is readable.

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/76616023/74a4912c-95f7-4489-8965-bf48e2f4c99f)

### On which device are you experiencing this bug?

Android, iPhone

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 
Can you assign me ?

**Comment by ashutosh-rath02** [comment]
Make them responsive and adjust colors for light screen. You have some previous assigned PR, please resolve them first

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 assign me this issue?

**Comment by ashutosh-rath02** [comment]
Hello @Shahbaz898414! Your issue #291 has been closed. Thank you for your contribution!
