### ISSUE TITLE
[Bug]: Profile Tracker Page - Scrolling Not Working Properly

### ISSUE THREAD

**Issue by Shahbaz898414** [ashutosh-rath02/git-re#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Scrolling is not working properly on the Profile Tracker page. Attempting to scroll on this page results in scrolling a different page instead.

### Expected behavior

Scrolling should work properly on the Profile Tracker page, allowing the user to scroll down the page itself.

### Add ScreenShots

https://github.com/ashutosh-rath02/git-re/assets/76616023/e773dac3-324c-405b-9e1b-421135e98787

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Shahbaz898414** [comment]
@ashutosh-rath02 
Can you assign  me this issue?

**Comment by ashutosh-rath02** [comment]
Hello @Shahbaz898414! Your issue #292 has been closed. Thank you for your contribution!
