### ISSUE TITLE
Improve Navbar UI

### ISSUE THREAD

**Issue by vanisharma2003** [ashutosh-rath02/git-re#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

UI of Navbar should be changed. According to me the styling that is given to navbar is very simple. It can be more better.

### Use Case

As navbar is the very first a user will notice. So it's UI should be eye catchy. So navbar UI should be changed.

### Benefits

Overall look of the website enhanced.

### Add ScreenShots

![Screenshot 2024-06-15 103047](https://github.com/ashutosh-rath02/git-re/assets/137780818/06818576-04ef-468e-8076-6cc9a288550b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Please provide mockup how you want to change it.

**Comment by vanisharma2003** [comment]
See I want to change hover effect and want to add a border type hover effect. Also I want to change font styling. I will use appropriate fonts that matches with website look. Also I am attaching the screenshot of the changes that I want to add.
![WhatsApp Image 2024-06-15 at 21 08 26_0f57489b](https://github.com/ashutosh-rath02/git-re/assets/137780818/1f5dde27-0c1d-4180-bad9-a507dcac196d)

**Comment by ashutosh-rath02** [comment]
Not needed as of now

**Comment by ashutosh-rath02** [comment]
Hello @vanisharma2003! Your issue #293 has been closed. Thank you for your contribution!
