### ISSUE TITLE
[Feature Request]: want to add stats like total users, total pageviews etc. below what our users say section.

### ISSUE THREAD

**Issue by VinayLodhi1712** [ashutosh-rath02/git-re#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

we can add stats page for good user experience (dummy data/numbers). It would look like 

https://github.com/ashutosh-rath02/git-re/assets/135756009/e3f52dd4-3e21-46c4-9ae7-4fb2fa24058c

i have done this in another project. 

### Use Case

enhance good user experience.

### Benefits

good user experience

### Add ScreenShots

Uploading features #89.mp4…

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by VinayLodhi1712** [comment]
plz assign me this @ashutosh-rath02 under gssoc label.

**Comment by ashutosh-rath02** [comment]
What are the stats you are planning to display?

**Comment by VinayLodhi1712** [comment]
> What are the stats you are planning to display?

total users(using leaderboard), pageclicks/pageviews of website, total followers on product-hunt or many more. We can use now dummy data for now if not available.

**Comment by ashutosh-rath02** [comment]
We will not using any dummy data, also how are you planning for pageclicks/pageviews?

**Comment by VinayLodhi1712** [comment]
> We will not using any dummy data, also how are you planning for pageclicks/pageviews?

we can use totalusers data using total no of users in leaderboards, also pageclicks we can use using https://www.hitwebcounter.com/ this website it will count total pageclicks. Also any other stats you want to display we can also use that.

**Comment by ashutosh-rath02** [comment]
That looks good but we are currently not looking to add an extra call here.

**Comment by ashutosh-rath02** [comment]
Hello @VinayLodhi1712! Your issue #294 has been closed. Thank you for your contribution!
