### ISSUE TITLE
feat: add husky workflow

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#3]
As we will be welcoming multiple contributors, we need that our codebase maintains a single code structure.

- [ ] Add husky setup
- [ ] Check if the setup is working

**Comment by VanshikaSabharwal** [comment]
i can add husky setup .please assign me this. i am a GSSOC contributor

**Comment by ashutosh-rath02** [comment]
@VanshikaSabharwal One issue at a time. Please resolve the previous one first😊

**Comment by VanshikaSabharwal** [comment]
Alright

**Comment by ashutosh-rath02** [comment]
Then ig you can start working on this one first😊

**Comment by VanshikaSabharwal** [comment]
Yes, Thank you

**Comment by ashutosh-rath02** [comment]
@VanshikaSabharwal Any update?

**Comment by VanshikaSabharwal** [comment]
Yes, i have added husky workflow and added pre-commits .the check will go on like this:-
1. Check types 
2. Check formatting of code
3. Check for lints
4. Will finally build the code
![Screenshot 2024-05-11 120221](https://github.com/ashutosh-rath02/git-re/assets/143436704/aa8774c8-f2ec-4fad-900a-9a3a57bcd28f)

**Comment by VanshikaSabharwal** [comment]
Just a few configurations and will be done. Any thing else which you would like to check in code before committing it ?

**Comment by ashutosh-rath02** [comment]
This should run on commit. Add pre-commit. It should check linting, prettier on commit. Also add eslint and prettier yml under workflow

**Comment by VanshikaSabharwal** [comment]
yes i have added it and it will run only on commit
