### ISSUE TITLE
feature: Add charts to show monthly activity

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#30]
Create a new section called profile tracking which will not be a part of resume and give an option to user to choose it.

- [x] Monthly and weekly activity tracking(Frequency and no. of commits)
- [x] Daily activity graph

**Comment by Bhumiba01** [comment]
i would like to work on this issue can you assign it to me

**Comment by ashutosh-rath02** [comment]
Sure @Bhumiba01 do you have any mockups in mind? Are you a GSSoC contributor?

**Comment by VanshikaSabharwal** [comment]
i am a GSSOC contributor and i want to work on this issue

**Comment by ashutosh-rath02** [comment]
Sure @VanshikaSabharwal please let me know what you are planning to do and I can assign you the issue.

**Comment by Vidip-Ghosh** [comment]
@ashutosh-rath02 we use github api to fetch the contributors data, in similar way we can fetch their github activities also. I can use chart.js to plot the graph.

**Comment by VanshikaSabharwal** [comment]
Hello @ashutosh-rath02 ,

Thank you for considering me for this task. I plan to use the GitHub API to fetch detailed activity data and employ Chart.js for creating intuitive daily, weekly, and monthly activity graphs. I'll ensure the feature is user-friendly with opt-in/out settings and maintain high accessibility standards. I’m ready to start and can provide frequent updates to keep the team informed.

**Comment by Bhumiba01** [comment]
Hey @ashutosh-rath02 yes I’m Gssoc contributor and in the profile tracking section I plan to  use drop down menu where user can select between weekly, daily and monthly activity. Use char.js for graph and GitHub APi

**Comment by ashutosh-rath02** [comment]
Ok @Bhumiba01 assigning you. You can take suggestions from @Vidip-Ghosh @VanshikaSabharwal to make it perfect

**Comment by ashutosh-rath02** [comment]
@Bhumiba01 Any updates?

**Comment by Bhumiba01** [comment]
@ashutosh-rath02 yes I'm working on it. and took suggestion from @Vidip-Ghosh

**Comment by ashutosh-rath02** [comment]
@VanshikaSabharwal you still want to work on this?

**Comment by VanshikaSabharwal** [comment]
> @VanshikaSabharwal you still want to work on this?

yes i want to work on it @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
@VanshikaSabharwal go ahead

**Comment by VanshikaSabharwal** [comment]
Hey @ashutosh-rath02 there is some error in the app functioning. See just check out the SS
![Screenshot 2024-05-18 183044](https://github.com/ashutosh-rath02/git-re/assets/143436704/1f7e9611-65c2-460c-a320-6884d92ef541)

**Comment by VanshikaSabharwal** [comment]
Hey @ashutosh-rath02 This issue is not resolved yet and i am not able to work 

> Hey @ashutosh-rath02 there is some error in the app functioning. See just check out the SS ![Screenshot 2024-05-18 183044](https://private-user-images.githubusercontent.com/143436704/331801448-1f7e9611-65c2-460c-a320-6884d92ef541.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzYyMTYsIm5iZiI6MTcxNjM3NTkxNiwicGF0aCI6Ii8xNDM0MzY3MDQvMzMxODAxNDQ4LTFmN2U5NjExLTY1YzItNDYwYy1hMzIwLTY4ODRkOTJlZjU0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxMTA1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTdhYzZlZjE1YmM5Nzc5ZmMxMWRiZDU1MmJhZDFmNTJlZDdmODc3YzAxMmYwZjY5ZDI4ZTUyYjg0NWQxOTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Luj-eAZGJjZDfRd5ibU5naWisBSCjNPKubqunMbMqEg)

**Comment by ashutosh-rath02** [comment]
@VanshikaSabharwal I hope it will be working fine now, else clear out your cache and check again

**Comment by VanshikaSabharwal** [comment]
okay @ashutosh-rath02

**Comment by VanshikaSabharwal** [comment]
@ashutosh-rath02 I did it still it is showing same error

**Comment by dhairyathedev** [comment]
> @ashutosh-rath02 I did it still it is showing same error

hey @VanshikaSabharwal, I have addressed this issue earlier today #157. To fix this issue from your end until my PR gets merged, you add some website/something to your github profile.

<img width="480" alt="Screenshot 2024-05-22 at 11 35 02 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/cad0433e-a538-4bba-8107-c425867bba90">

**Comment by ashutosh-rath02** [comment]
@VanshikaSabharwal any updates?

**Comment by VanshikaSabharwal** [comment]
> @VanshikaSabharwal any updates?

Yes @ashutosh-rath02  ,I'll raise PR in 1-2 day

**Comment by Sid-80** [comment]
@ashutosh-rath02 I am willing to work on this issue

**Comment by ashutosh-rath02** [comment]
Go ahead @Sid-80

**Comment by Sid-80** [comment]
@ashutosh-rath02 I have to add new section here right!

![image](https://github.com/ashutosh-rath02/git-re/assets/101277141/3b70777d-593d-4f07-9790-062d37e36a55)

**Comment by Sid-80** [comment]
@ashutosh-rath02 I think it would be great if we add a button near to Customize Resume

**Comment by Sid-80** [comment]
![image](https://github.com/ashutosh-rath02/git-re/assets/101277141/ecbde9bb-0b49-4763-9d0a-d62b2fd0f741)

**Comment by Sid-80** [comment]
And one more thing should I create a separate route for it or just a modal like thing ?

**Comment by Sid-80** [comment]
Glimpse of Daily activity

https://github.com/ashutosh-rath02/git-re/assets/101277141/87ee61f0-7c64-4c9e-bedb-80d81d08e959

**Comment by Sid-80** [comment]
@ashutosh-rath02  Also only a recent 30 events are returned from github api of events we cannot get monthly tracking!
Let me know if you having any idea!

**Comment by Sid-80** [comment]
![image](https://github.com/ashutosh-rath02/git-re/assets/101277141/64d7347c-4fb1-4894-a410-8c8413c110d0)

![image](https://github.com/ashutosh-rath02/git-re/assets/101277141/b3be6b49-6572-4b22-a684-6e1edf71bfea)

**Comment by ashutosh-rath02** [comment]
@dhairyathedev as you have developed the design you can have a look too here and give your suggestions

**Comment by ashutosh-rath02** [comment]
Where are you placing this feature can you show?

**Comment by Sid-80** [comment]
![image](https://github.com/ashutosh-rath02/git-re/assets/101277141/412b6d1a-70a1-4da1-be41-4efe80c06b9e)

**Comment by dhairyathedev** [comment]
Adjust the text contrast here.

<img width="814" alt="Screenshot 2024-06-10 at 10 57 49 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/670c7133-fa97-41db-bb02-dbba5629e3e7">

Otherwise, it looks good to me. You can go ahead and open the PR.

**Comment by ashutosh-rath02** [comment]
@dhairyathedev if the user doesn't have a website link, then we can omit displaying blank.

**Comment by dhairyathedev** [comment]
> @dhairyathedev if the user doesn't have a website link, then we can omit displaying blank.

Good catch @ashutosh-rath02 , I will fix that.

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #30 has been closed. Thank you for your contribution!
