### ISSUE TITLE
[Bug]: Hover effects in Navbar & footer

### ISSUE THREAD

**Issue by aanchalpahuja18** [ashutosh-rath02/git-re#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On hovering the navbar & footer doesn't change the styling of the elements.

### Expected behavior

Hovering on navbar & footer should look different from the existing styling of the elements 

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/136963878/b32596df-d5a8-4ea4-bf1d-f9333bfd5cc8)
![image](https://github.com/ashutosh-rath02/git-re/assets/136963878/60541769-a396-4c88-a112-593e3047c07b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by aanchalpahuja18** [comment]
@ashutosh-rath02 Kindly assign me this issue I will resolve it really quick & submit it to you.

**Comment by ashutosh-rath02** [comment]
Not needed as of now

**Comment by ashutosh-rath02** [comment]
Hello @aanchalpahuja18! Your issue #301 has been closed. Thank you for your contribution!
