### ISSUE TITLE
[Feature Request]: Adding 404 not found page or redesigning the page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [ashutosh-rath02/git-re#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/ashutosh-rath02/git-re/assets/125277258/1fd49478-c5ae-4f50-acce-aa3ba640d827)

### Use Case

if we send the req to an unknown URL then the 404 not found page will come

### Benefits

![image](https://github.com/ashutosh-rath02/git-re/assets/125277258/d326b6f7-9918-4850-a830-5cdcf875fa0e)
  
here it looks like 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by RamakrushnaBiswal** [comment]
hi @ashutosh-rath02 i want to work upon the issue

**Comment by ashutosh-rath02** [comment]
Go ahead @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
solved via #303

**Comment by ashutosh-rath02** [comment]
Hello @RamakrushnaBiswal! Your issue #302 has been closed. Thank you for your contribution!
