### ISSUE TITLE
[Feature Request]: Social media icon enhancement

### ISSUE THREAD

**Issue by Damini2004** [ashutosh-rath02/git-re#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Icons should be more tempting after adding suitable hover effects.

### Use Case

That will be more beneficial for user engagement

### Benefits

More number of user engagement

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/119414762/8e763ce8-3b78-4911-ba5c-9fe8a46f6a91)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
We are keeping these changes for a hold now. You can look into our existing issues.

**Comment by ashutosh-rath02** [comment]
Hello @Damini2004! Your issue #305 has been closed. Thank you for your contribution!
