### ISSUE TITLE
[Feature Request]: Addition of Custom Animated Cursor

### ISSUE THREAD

**Issue by HishitaGupta** [ashutosh-rath02/git-re#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a circular custom animated cursor.

### Use Case

This will enhance the UI of the website.

### Benefits

Will give the site a modern look.

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/159264060/e8430b33-e4c9-470c-b7c8-7d6e6576d049)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hey @HishitaGupta this doesn't look good, can you provide some other cursors which look like arrow.

**Comment by ashutosh-rath02** [comment]
Hello @HishitaGupta! Your issue #308 has been closed. Thank you for your contribution!
