### ISSUE TITLE
[Feature Request]: Make the Navbar Sticky and addition of Frosted Glass effect on Navbar

### ISSUE THREAD

**Issue by HishitaGupta** [ashutosh-rath02/git-re#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Make the Navbar Sticky and addition of Frosted Glass effect on Navbar

### Use Case

Will enhance the UI of the website.

### Benefits

Will enhance the UI of the website.

### Add ScreenShots

![image](https://github.com/ashutosh-rath02/git-re/assets/159264060/688b90d2-415a-4b53-b8cc-b04f10416c4b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @HishitaGupta! Your issue #309 has been closed. Thank you for your contribution!
