### ISSUE TITLE
feature: show recent profile generations

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#31]
- [ ] Add a section in the homepage with good UI showing recent profiles
- [ ] Store the usernames and data in mongodb and display
- [ ] Should be clickable and redirect to respective profiles only when logged in

**Comment by mohdjami** [comment]
Hi @ashutosh-rath02 . I am interested to work on this issue. I have relevant exprience in Nextjs. Please assign me this issue for GSSoC'24.

**Comment by ashutosh-rath02** [comment]
Hey @mohdjami, welcome!! Can you please brief how you are planning to solve the issue?

**Comment by RoopsagarK** [comment]
Hello, @ashutosh-rath02 iam intrested to work on this issue. I just seen the project  we can get the gitHub_uername  when the user click the generate button and store it in mongodb, then we can create a section just below the hero section displaying the recent generates in cards which on click will be redirected to the /resume/git_resume. Looking forward for your response willing to contribute to git-re has GSSOC'24 contributor.

**Comment by RoopsagarK** [comment]
@ashutosh-rath02 Thank you for your response

**Comment by mohdjami** [comment]
@RoopsagarK If you have started working on this issue, should I find any other issue? @ashutosh-rath02 Or two people can raise PRs?

My approach was also similar I would build a profiles section in the landing page accessible only to logged in users using Shadcn UI. I will create a schema to store the usernames and data in Mongodb. On clicked it will be redirected to the respected profile by passing the id in a post request. I had some doubts before start working on the issue that I will clear if I start working.

**Comment by ashutosh-rath02** [comment]
Hey @mohdjami @RoopsagarK is currently working on it. You can look into some other issue or create some more issues. New features will be Level 3 contributions😊

**Comment by RoopsagarK** [comment]
Added the recent profile generations section just below the hero section. I have raised PR I kindly request a review of my code and appreciate any further suggestions for improvement.

**Comment by RoopsagarK** [comment]
https://github.com/ashutosh-rath02/git-re/assets/107497296/198d7436-0e50-4f4a-9039-e142b8fa0a7e

Here is the video of the added feature!😁
