### ISSUE TITLE
[Feature Request]: Addition of About us page

### ISSUE THREAD

**Issue by CoderGirl2844** [ashutosh-rath02/git-re#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

About Us page option can be added in the nav bar

### Use Case

About Us page will let users know more about the website and its features

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @CoderGirl2844! Your issue #310 has been closed. Thank you for your contribution!
