### ISSUE TITLE
[Feature Request]: Adding a Login Page

### ISSUE THREAD

**Issue by Ojas-Arora** [ashutosh-rath02/git-re#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@ashutosh-rath02 I want to add a login/signup page. Kindly assign this issue to me.

### Use Case

NA

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
We are allowing only github oauth adding an extra screen wont look good

**Comment by ashutosh-rath02** [comment]
Hello @Ojas-Arora! Your issue #313 has been closed. Thank you for your contribution!
