### ISSUE TITLE
[UI Enhancement] - Footer and Navbar can be redesigned.

### ISSUE THREAD

**Issue by NilanchalaPanda** [ashutosh-rath02/git-re#32]
The footer section of Git-re is currently looking very simple and does not really align with the design. Here some improvements can be done in the with the help of Tailwind CSS. The Navbar is not optimized for mobile version, which can be achieved easily with the help of Tailwind CSS and simple enhancements.

Would love to work on this issue as a GSSoC'24 Contributor. Lookin forward for your response.
IMAGE : 
**Footer :**
![image](https://github.com/ashutosh-rath02/git-re/assets/110488337/56636cdf-8f18-4dc8-ae76-da60a6b54047)

**Navbar :**
![image](https://github.com/ashutosh-rath02/git-re/assets/110488337/1e40444e-c5af-4d56-bf6c-a527649d9a04)

**Comment by rajat4984** [comment]
For the navbar, we can make the Git-RE logo smaller and add the buttons for fork, login, and dark mode to the hamburger menu. I would love to work on this issue. Could you please assign it to me?

**Comment by Karankumar2004** [comment]
Hey @ashutosh-rath02  as I have expertise in frontend development and UI/UX design, I'd like to address this issue. Could you please assign it to me under GSSoc 24'?
