### ISSUE TITLE
[Bug]: Data is NULL. User is rate-limited by GitHub" error

### ISSUE THREAD

**Issue by Swastik19Nit** [ashutosh-rath02/git-re#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current code checks if userData.name is null or empty to determine if the user is rate-limited. However, this might not be the most reliable method, as some users might genuinely have no name set on their GitHub profile. So it should be changed to userData.username.

### Expected behavior

userData.username should be used here.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Swastik19Nit** [comment]
PR #321 solves this issue

**Comment by ashutosh-rath02** [comment]
Hello @Swastik19Nit! Your issue #324 has been closed. Thank you for your contribution!
