### ISSUE TITLE
[Bug]: The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This error occurs in the development because, the `next.config.js` is using deprecated image configuration.

### Expected behavior

Next.js image configuration needs to be changed to the latest configuration.

### Add ScreenShots

<img width="1023" alt="Screenshot 2024-06-27 at 3 49 42 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/3c3e82ba-d289-430c-93a6-4d0bf6e2f44e">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #328 has been closed. Thank you for your contribution!
