### ISSUE TITLE
[Feature Request]: Add Scroll To Up Feature

### ISSUE THREAD

**Issue by VaishnaviMankala19** [ashutosh-rath02/git-re#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add scroll to up to the project

### Use Case

A "scroll to top" button enhances user experience on webpages by providing a quick navigation option. It improves usability

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Go ahead @VaishnaviMankala19

**Comment by ashutosh-rath02** [comment]
Hello @VaishnaviMankala19! Your issue #330 has been closed. Thank you for your contribution!
