### ISSUE TITLE
[Feature Request]: Adding hover effects to the star on github button

### ISSUE THREAD

**Issue by Rajul-29** [ashutosh-rath02/git-re#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hover effects can be added to the star on github button for improved user experience and increased engagement

### Use Case

Hover effects provide feedback and confirmation and increases usability

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Rajul-29** [comment]
Hey @ashutosh-rath02!
I would like to work on this issue, Can you please assign it to me under GSSOC'24
Thank you

**Comment by ashutosh-rath02** [comment]
Not required as of now.

**Comment by ashutosh-rath02** [comment]
Hello @Rajul-29! Your issue #331 has been closed. Thank you for your contribution!
