### ISSUE TITLE
[Bug]: Issues with the radar

### ISSUE THREAD

**Issue by Swastik19Nit** [ashutosh-rath02/git-re#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The radar chart is not correctly responding to the system's color (System mode is not working). Also There's a small typo in the data mapping for issues that's why it is not getting pointed in the radar.

### Expected behavior

after the correction it will work properly like this in system mode as well
![image](https://github.com/ashutosh-rath02/git-re/assets/122457803/2ffcf115-1aa7-4604-8372-0a6bb7f0d6dd)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Swastik19Nit** [comment]
![image](https://github.com/ashutosh-rath02/git-re/assets/122457803/9a17887d-b170-4b19-bb74-82f50dd4e049)
this is what it looks now... now i realized what's the mistake. i forgot to set the theme for systems here and also there is a typo due to which it will display only 3 parameters instead of 4.

**Comment by ashutosh-rath02** [comment]
GO ahead @Swastik19Nit

**Comment by dhairyathedev** [comment]
Hey @Swastik19Nit,

Do the changes to your issue after #336 this PR gets merged. Or else there will be merge conflicts.

@ashutosh-rath02 give #336 a priority. So, Swastik can work on this issue.

**Comment by ashutosh-rath02** [comment]
@dhairyathedev Your recent issue aligns much with this one. You can guide @Swastik19Nit what needs to be done here only

**Comment by Swastik19Nit** [comment]
![image](https://github.com/ashutosh-rath02/git-re/assets/122457803/3487023b-8b9e-4ffc-b8b5-73ee8fc1cff9)
i have solved the issue of the ticks as well.. now it will be dynamically calculated on the radar and will be displayed neat

**Comment by ashutosh-rath02** [comment]
Ok raise a PR @Swastik19Nit

**Comment by dhairyathedev** [comment]
> ![image](https://private-user-images.githubusercontent.com/122457803/344447463-3487023b-8b9e-4ffc-b8b5-73ee8fc1cff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzIyNzksIm5iZiI6MTcxOTczMTk3OSwicGF0aCI6Ii8xMjI0NTc4MDMvMzQ0NDQ3NDYzLTM0ODcwMjNiLThiOWUtNGZmYy1iOGI1LTczZWU4ZmMxY2ZmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNzE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmIyMGEwOGU0NWJiZDhhMDU2YTMwNzFhZmIxNDEyM2U4ZTc4ZDBjNjgzMTRjMjgwMmExNjQxZWIwYmIyZDU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uvXC9IGidf6qcVYnnpVpuw5Aly-X0-f-6ntLL9sfZCQ) i have solved the issue of the ticks as well.. now it will be dynamically calculated on the radar and will be displayed neat

How are you setting the tick count? Fixed count or programmatically? @Swastik19Nit

**Comment by Swastik19Nit** [comment]
The calculateStepSize function uses logarithms and powers of 2 to find a step size that's easy to read (like 20, 50, 100, etc.) and that dividdes the max value into a reasonable number of steps. This makes sure that the radar chart remains readable regardless of whether the users stats are in tens, hundreds, or thousands.
@ashutosh-rath02

**Comment by Swastik19Nit** [comment]
I have raised a common PR

**Comment by ashutosh-rath02** [comment]
Hello @Swastik19Nit! Your issue #332 has been closed. Thank you for your contribution!
