### ISSUE TITLE
Feature: Compare for the non-existing user in the database

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#333]
### Issue
Currently, compare feature doesn't allow to compare the users who are not in the database.

### Expected behavior
Any profile can be compared, irrespective of their presence in database

Please assign this issue to me

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
GO ahead @dhairyathedev

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #333 has been closed. Thank you for your contribution!

**Comment by ashutosh-rath02** [comment]
@dhairyathedev this hasn't been fixed yet

**Comment by dhairyathedev** [comment]
@ashutosh-rath02  Actually, it was working locally. Let me check the cause.

**Comment by dhairyathedev** [comment]
Working completely fine in the local dev server

https://github.com/ashutosh-rath02/git-re/assets/65452005/c655f348-6a64-4dbd-baa7-9e86cd48fd2c

**Comment by dhairyathedev** [comment]
@ashutosh-rath02 can you just rebuild and deploy the site on Vercel. This might fix the issue.

**Comment by dhairyathedev** [comment]
@ashutosh-rath02 This also works on my self hosted version of the main branch of the fork - https://git-re.dhairyashah.dev/compare

**Comment by ashutosh-rath02** [comment]
![image](https://github.com/ashutosh-rath02/git-re/assets/85403534/06b136fb-5de9-42b4-8d3d-189d51a9716e)
Na dude still not working, I redeployed the latest commit without cache
![image](https://github.com/ashutosh-rath02/git-re/assets/85403534/0fcfeb93-abaa-4a4f-ae9b-818e28d1ace4)

**Comment by dhairyathedev** [comment]
That's very strange! 

Let's discuss on Discord @ashutosh-rath02.

**Comment by ashutosh-rath02** [comment]
Ok it's working now. Good understanding @dhairyathedev

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #333 has been closed. Thank you for your contribution!
