### ISSUE TITLE
refactor: Radar chart components needs to be re-written in typescript.

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#335]
### Issue
As the whole codebase of git-re is in Typescript, the new component `RadarChart.jsx` needs to re-written in Typescript.

Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #335 has been closed. Thank you for your contribution!
