### ISSUE TITLE
bug: too many ticks make the Radar chart

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#337]
### Issue
If the user profile comparison has more than 200 commits, viewing the ticks label is difficult. 

### Expected behaviour
Fix number of ticks should be shown, in this case, 5 is suitable. But the difference will be instead of hardcoding the step value, we will programmatically generate the ticks label. 

Hardcoding the value to 5 will look like this, which looks even worse than the current version:
<img width="1071" alt="Screenshot 2024-06-30 at 12 08 32 AM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/cc582954-b23e-44f2-bfb5-1016d67cc662">

### Screenshot

**Before:**

<img width="962" alt="Screenshot 2024-06-30 at 12 08 14 AM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/3a924a55-9dcd-4ef3-8c86-3394117151da">

**After:**

<img width="720" alt="Screenshot 2024-06-30 at 12 09 27 AM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/e8b801f3-5155-4da1-aa89-5542a4f4ae9a">

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #337 has been closed. Thank you for your contribution!

**Comment by ashutosh-rath02** [comment]
Check #339 and guide further
