### ISSUE TITLE
[Feature Request]: Design a FAQ section

### ISSUE THREAD

**Issue by komal-agarwal5** [ashutosh-rath02/git-re#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Design a FAQ section using accordions

### Use Case

It will improve user experience of the overall website

### Add ScreenShots

![Screenshot 2024-06-30 210117](https://github.com/ashutosh-rath02/git-re/assets/122633300/afe6d543-e983-4997-80e0-202b72123223)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
@komal-agarwal5 Go ahead but please mention the questions that you are going to use

**Comment by ashutosh-rath02** [comment]
Let's discuss those on the discord channel. You can join here https://discord.com/channels/1231112132595028008/1231119005536878612/1240684613530292375

**Comment by ashutosh-rath02** [comment]
Hello @komal-agarwal5! Your issue #340 has been closed. Thank you for your contribution!
