### ISSUE TITLE
[Feature Request]: Share button on new resume page

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#350]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

Sharing features on new resume page

### Use Case

Ease to share the Resume profile

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #350 has been closed. Thank you for your contribution!
