### ISSUE TITLE
[Bug]: New users added through compare are not able to generate resume

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a non-existing user is added to the database using the compare feature, and later visits the landing page to generate their resume by entering their GitHub username, they will encounter an internal server error.

### Expected behavior

Non exisiting users added through compare page can be able to generate the resume from landing page as usual.

### Add ScreenShots

https://github.com/ashutosh-rath02/git-re/assets/65452005/4c98ca30-cec2-43d3-9018-2f98eb90775a

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Why is this happening?

**Comment by dhairyathedev** [comment]
> Why is this happening?

@ashutosh-rath02 this is happening because of outdated validation checks on the `/api/users`.

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #352 has been closed. Thank you for your contribution!
