### ISSUE TITLE
[Feature Request] : AI cover letter generation

### ISSUE THREAD

**Issue by Sid-80** [ashutosh-rath02/git-re#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am willing to add a feature like cover letter generation using our GitHub generated resume and user can also provide their own resume.

### Use Case

Not only user will visit to generate resume but cover letter generation too. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Sid-80** [comment]
@ashutosh-rath02 I am willing to work on this issue!!

**Comment by ashutosh-rath02** [comment]
> @ashutosh-rath02 I am willing to work on this issue!!

I was looking into AI integration, we need to discuss on the workflow properly. Let's talk on discord, you can join the git-re channel.

**Comment by Sid-80** [comment]
@ashutosh-rath02 Yes sure!!
Let me know when you will be available...

**Comment by ashutosh-rath02** [comment]
Drop a message in the git-re channel we can hop on a meet tomorrow 10-11

**Comment by ashutosh-rath02** [comment]
Hello @Sid-80! Your issue #356 has been closed. Thank you for your contribution!
