### ISSUE TITLE
[Feature Request]: Add a scroll to the top button

### ISSUE THREAD

**Issue by Rajul-29** [ashutosh-rath02/git-re#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a "Scroll to Top" button enhances user experience by providing quick navigation back to the top of the page

### Use Case

It reduces the effort required for manual scrolling, improving accessibility and convenience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Rajul-29** [comment]
Hey @ashutosh-rath02!
Can you this issue to me under GSSOC'24
Thank you

**Comment by ashutosh-rath02** [comment]
Not needed feature,

**Comment by ashutosh-rath02** [comment]
Hello @Rajul-29! Your issue #357 has been closed. Thank you for your contribution!
