### ISSUE TITLE
[Feature Request]: Add hover effects to navbar links

### ISSUE THREAD

**Issue by Rajul-29** [ashutosh-rath02/git-re#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding hover effects to navbar links enhances the user experience by providing immediate visual feedback, indicating interactivity and guiding navigation

### Use Case

They will help to improve the website's aesthetics and usability, making it more engaging and intuitive. Hover effects can also highlight important links, increasing user awareness and encouraging exploration, ultimately leading to a more dynamic and appealing interface.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Not needed

**Comment by ashutosh-rath02** [comment]
Hello @Rajul-29! Your issue #358 has been closed. Thank you for your contribution!
