### ISSUE TITLE
[Cover Letter]: Multi Step Form Modal

### ISSUE THREAD

**Issue by Sid-80** [ashutosh-rath02/git-re#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am willing to create modal as multi step form to take following parameters as input :
1. Job description
2. Are they willing to add there own resume or we can make use of github resume. They can also add skill, experience, projects....
Finally, generate...

It will also contain form validation and responsiveness.

Let me know if any things to be added.

### Use Case

It will add another feature to our website which will attract users.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @Sid-80! Your issue #360 has been closed. Thank you for your contribution!
