### ISSUE TITLE
[Feature Request]: Add profile views

### ISSUE THREAD

**Issue by root-0101** [ashutosh-rath02/git-re#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add number of profile view in the compare section for a GitHub username

### Use Case

adding this feature will be effective to compare both the profiles

### Add ScreenShots

![Screenshot 2024-07-04 215811](https://github.com/ashutosh-rath02/git-re/assets/142779809/66d11d1d-ac22-441e-af9c-d42ab730bdb2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @root-0101! Your issue #361 has been closed. Thank you for your contribution!
