### ISSUE TITLE
[Feature Request]: Create search user functionality in leaderboard

### ISSUE THREAD

**Issue by komal-agarwal5** [ashutosh-rath02/git-re#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Create search user functionality in leaderboard page

### Use Case

As the number of users of the product will increase it will become difficult for users to find their position in the leaderboard,hence search functionality will help to search up their rank or their peers rank 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @komal-agarwal5! Your issue #365 has been closed. Thank you for your contribution!
