### ISSUE TITLE
[Feature Request]: Add contact page with contact form

### ISSUE THREAD

**Issue by krishnas005** [ashutosh-rath02/git-re#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to add a contact page to our project that includes a user-friendly contact form. This form should allow users to enter their details (name, email, and message) and send queries directly to a specified email address. The page should be designed to be responsive, ensuring a seamless experience on both desktop and mobile devices.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Not required as of now

**Comment by ashutosh-rath02** [comment]
Hello @krishnas005! Your issue #366 has been closed. Thank you for your contribution!
