### ISSUE TITLE
[Feature Request]: Add a Terms and Conditions Page. I want to contribute under GSSOC' 24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [ashutosh-rath02/git-re#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Terms and Conditions Page and give the respective link in the footer of the page. 

### Use Case

This page will give the terms and conditions associated with the website. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Not required

**Comment by ashutosh-rath02** [comment]
Hello @ParnaRoyChowdhury777! Your issue #367 has been closed. Thank you for your contribution!
