### ISSUE TITLE
[AI]: Integrate Gemini

### ISSUE THREAD

**Issue by Sid-80** [ashutosh-rath02/git-re#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am willing to integrate the Gemini model for AI Cover letter Generation 

### Use Case

Automate the process of cover letter generation 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
@Sid-80 updates?

**Comment by Sid-80** [comment]
@ashutosh-rath02 Sorry bro, I was busy with placements will be done in 2-3 days

**Comment by ashutosh-rath02** [comment]
Hello @Sid-80! Your issue #377 has been closed. Thank you for your contribution!
