### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [ashutosh-rath02/git-re#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Use Case

It will Enhance User Experience 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead @sailaja-adapa

**Comment by sailaja-adapa** [comment]
Okk @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
Hello @sailaja-adapa! Your issue #379 has been closed. Thank you for your contribution!
