### ISSUE TITLE
Add Icons To Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [ashutosh-rath02/git-re#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add icons to Navbar
Can you assign me this issue under GSSOC'24 

![IMG_20240715_130632](https://github.com/user-attachments/assets/21bc182d-f8f3-4abc-87a6-bce7f5eb72e3)

### Use Case

It will increase website Attractiveness 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Hello @sailaja-adapa! Your issue #380 has been closed. Thank you for your contribution!
