### ISSUE TITLE
[Feature Request]: AI-Limit

### ISSUE THREAD

**Issue by Sid-80** [ashutosh-rath02/git-re#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am willing to add a limit to the usage of AI.
User can generate the cover letter for 2 times per day.

### Use Case

To limit the usage of Gemini API.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Please add it ASAP.

**Comment by dhairyathedev** [comment]
Hey @Sid-80, can you also update the `.env.example` file for the latest secrets configuration of Conver letter generation.

**Comment by ashutosh-rath02** [comment]
@Sid-80 updates?

**Comment by ashutosh-rath02** [comment]
Hello @Sid-80! Your issue #391 has been closed. Thank you for your contribution!
