### ISSUE TITLE
[Feature Request]: Create a good loader

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current loader after clicking on build resume doesn't look good, add something new.

### Use Case

Enhancement

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2df65e1b-c845-4bd8-a6c0-869d2176bddf)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by komal-agarwal5** [comment]
@ashutosh-rath02 I would like to work on this, can you please assign it to me?
Also is there any particular loader design you want me to implement, or I can try something from my side?

**Comment by ashutosh-rath02** [comment]
You can try something. Send it in discord so that we can discuss.

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #395 has been closed. Thank you for your contribution!
