### ISSUE TITLE
[Feature Request]: Add a Google Language Translator

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [ashutosh-rath02/git-re#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wish to add a Google Language translator in the page.

### Use Case

This will help users to read the content in different languages.

### Benefits

Improves user experience and readability.

### Add ScreenShots

![Screenshot 2024-07-20 065125](https://github.com/user-attachments/assets/d6846662-020c-43b0-8776-f5c619997c60)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Where are you planning to add this feature?

**Comment by ParnaRoyChowdhury777** [comment]
> Where are you planning to add this feature?

I was thinking to add this feature in the footer of the website.

**Comment by ashutosh-rath02** [comment]
ok go ahead

**Comment by ashutosh-rath02** [comment]
Closing this as stale

**Comment by ashutosh-rath02** [comment]
Hello @ParnaRoyChowdhury777! Your issue #399 has been closed. Thank you for your contribution!
