### ISSUE TITLE
Discussion: New features

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#4]
We have implemented few basic public information but according to my research we can implement many different features when users allow us through token. 
We need to discuss the features and their implementations.

**Comment by Dhananjayshukla1** [comment]
@ashutosh-rath02 which type of new features? could you plz explain it.

**Comment by ashutosh-rath02** [comment]
Here we can discuss what new features can be added to git-re and then raise issues accordingly.

**Comment by TANJIRO1709** [comment]
can you asssign me this issue

**Comment by Nkmeoo7** [comment]
> Here we can discuss what new features can be added to git-re and then raise issues accordingly.

so ashutosh you want a chat secation where we can about new features and how we gonna solve it and raise pr accordingly?

**Comment by ashutosh-rath02** [comment]
No no @Nkmeoo7 this issue doesnt lead to any specific problem. Its just an discussion issue

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #4 has been closed. Thank you for your contribution!
