### ISSUE TITLE
[Bug]: Leaderboard shows infinite loading when no search results are found

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When searching for a term which is not present in the leaderboard will result in infinite skeleton loading state.

### Expected behavior

It must show no results found.

### Add ScreenShots

<img width="1450" alt="Screenshot 2024-07-22 at 9 28 54 PM" src="https://github.com/user-attachments/assets/e45fffef-7d9d-4099-8c31-fc3a6a78a2ad">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
@dhairyathedev updates?

**Comment by dhairyathedev** [comment]
> @dhairyathedev updates?

Sorry @ashutosh-rath02 for delays, I was busy. I will try to finish this by today

**Comment by ashutosh-rath02** [comment]
Hello @dhairyathedev! Your issue #406 has been closed. Thank you for your contribution!
