### ISSUE TITLE
[Bug]:  CSS of FAQs page in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [ashutosh-rath02/git-re#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

css of FAQs section is uneven in mobile view

### Expected behavior

css should be fixed 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/494eea07-4c6b-497f-a037-25d979c8e993)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by dhairyagothi** [comment]
@ashutosh-rath02 please assign

**Comment by ashutosh-rath02** [comment]
Duplicate

**Comment by ashutosh-rath02** [comment]
Hello @dhairyagothi! Your issue #407 has been closed. Thank you for your contribution!
