### ISSUE TITLE
Floating Navbar which will go up on scroling and come again on scrolling up see DEMO

### ISSUE THREAD

**Issue by Utsavladia** [ashutosh-rath02/git-re#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It should be on the top so users can use it froom anywhere in the website

### Use Case

it should be on the top 

### Add ScreenShots

https://github.com/user-attachments/assets/7cd33d75-4b56-4d52-8efb-f3a4cb7c8570

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Utsavladia** [comment]
@ashutosh-rath02 
Thre is some issuue related to the supabase
![image](https://github.com/user-attachments/assets/3656db56-db37-4842-b996-1c32850ef481)


Kindly suggest me how to fix it or get it fixed then i'll sync and start working on this issue...

**Comment by ashutosh-rath02** [comment]
Hello @Utsavladia! Your issue #414 has been closed. Thank you for your contribution!
