### ISSUE TITLE
Made Navbar responsive for all screen sizes

### ISSUE THREAD

**Issue by Utsavladia** [ashutosh-rath02/git-re#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/6590e1f1-f28b-4797-9ca1-13eb65628ad4)

### Use Case

It should be fixed with all the sizes and paddings to give a uniform look

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead @Utsavladia

**Comment by ashutosh-rath02** [comment]
Hello @Utsavladia! Your issue #415 has been closed. Thank you for your contribution!
