### ISSUE TITLE
Login Butten on hover

### ISSUE THREAD

**Issue by rishabh-bijalwan12** [ashutosh-rath02/git-re#42]
Login Butten on hover its text not readable and improving ui (adding scale on hover) in linkedin, github icon at footer

![image](https://github.com/ashutosh-rath02/git-re/assets/116650217/c31e82ca-7749-4486-9caf-c2a9398163b4)

**Comment by rishabh-bijalwan12** [comment]
Kindly assign me this issue  under GSSOC'24

**Comment by MishraTanishq619** [comment]
should i do it like this,
on Hover to button : bg lightish , font blackish

**Comment by ashutosh-rath02** [comment]
@rishabh-bijalwan12 are you gonna work on it or should I merge @MishraTanishq619 PR?

**Comment by rishabh-bijalwan12** [comment]
I want to work on it you have not assigned me that why I not start working

**Comment by rishabh-bijalwan12** [comment]
Working on it
