### ISSUE TITLE
[Feature Request]: The testimonials link in navbar isn't working when viewed on small screens.

### ISSUE THREAD

**Issue by AlaynaShaheen** [ashutosh-rath02/git-re#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The testimonials link in navbar isn't responsive. I am a contributor in GSSoC' 24. I can solve this issue as I have worked upon similar issues earlier.
Please assign this task to me under GSSoC'24.

### Use Case

Testimonials link should be redirected to home page testimonials section but the feature is actually not working.

### Add ScreenShots

https://github.com/user-attachments/assets/0c7f122c-5179-4a90-a9f4-756d5b406025

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ashutosh-rath02** [comment]
Go ahead @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
Thanks for assigning the issue @ashutosh-rath02. I'll resolve the issue and raise a PR soon.

**Comment by AlaynaShaheen** [comment]
Actually after analyzing the code I found that there is no testimonials page seperately and when we click on testimonials tab it is getting redirected to the testimonials section of the same home page. Sorry for the issue created. @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
Hello @AlaynaShaheen! Your issue #421 has been closed. Thank you for your contribution!
