### ISSUE TITLE
Add Newsletter and Legal Information to Footer

### ISSUE THREAD

**Issue by lovelymahor** [ashutosh-rath02/git-re#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current footer lacks both a newsletter subscription section and legal information. The request is to add these elements to the footer for better user engagement and compliance.

### Use Case

Adding these elements will enhance user engagement through the newsletter and ensure compliance with legal requirements by providing necessary legal information.

### Benefits

It will improve user engagement, ensure compliance with legal standards, and provide a more comprehensive and professional footer.

### Add ScreenShots

![Screenshot (304)](https://github.com/user-attachments/assets/53296081-9337-4145-a2bc-96ddc9ff2781)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by lovelymahor** [comment]
@ashutosh-rath02 I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by ashutosh-rath02** [comment]
@lovelymahor We currently do not have any news letter or are binding people with any legal terms

**Comment by ashutosh-rath02** [comment]
Hello @lovelymahor! Your issue #422 has been closed. Thank you for your contribution!
