### ISSUE TITLE
feat: add sharing feature

### ISSUE THREAD

**Issue by ratishjain12** [ashutosh-rath02/git-re#43]
I want to add share options after generating the resume with the help of which user can directly share the resume link to others or share on twitter

@ashutosh-rath02 kindly assign it to me under GSSoC'24

**Comment by ashutosh-rath02** [comment]
That's a great idea @ratishjain12 . Are you planning to include og-tags so that when you share it looks good? We just don't want to share blank link.

**Comment by ratishjain12** [comment]
Yeah I can do that if that is what's needed :)

**Comment by ashutosh-rath02** [comment]
Any other method is appreciated too😄

**Comment by ratishjain12** [comment]
So basically when we share the links we want to show a Image and title right for the link during sharing

**Comment by ashutosh-rath02** [comment]
@ratishjain12 It should contain a card with Git-re, username of user, and profile picture displayed. We can place some cool text as title and description.

**Comment by ratishjain12** [comment]
Aight on it

**Comment by ashutosh-rath02** [comment]
@ratishjain12 any updates?

**Comment by ratishjain12** [comment]
> @ratishjain12 any updates?

Almost done!
