### ISSUE TITLE
Chore : Create social media post for GSSoC

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#435]
We have been part of GSSoC '24 from the beginning and git-re has grown a lot with all contributions by the peeps. Draft a linkedin post regarding the Git-re in GSSoC '24, all the features implemented, etc. 
Easy Level 3

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by VinayakPaka** [comment]
Can u please assign it to me .

**Comment by ashutosh-rath02** [comment]
Can you tell me what would be your procedure?

**Comment by vansh-codes** [comment]
@ashutosh-rath02 Hi, I can help you create a linkedin post about the journey
As I havent contributed in this repo, so the approach I will follow is to go through the initial commits to understand the former features and ui of git-re and gradually moving to the latest commit describing the journey throughout this 3months.

**Comment by ashutosh-rath02** [comment]
Great that sounds good. Please do it by today EOD if possible. Keep it in a google doc and share the link

**Comment by vansh-codes** [comment]
https://1drv.ms/w/s!Aq5VTv5cfNM2qDnTWbPCtioC94gF?e=tiB4wn

Here you go @ashutosh-rath02 
I am sharing link from google doc for the first time, I hope it works fine :(

**Comment by vansh-codes** [comment]
[GIT.docx](https://github.com/user-attachments/files/16560148/GIT.docx)

You can download the document from here @ashutosh-rath02

**Comment by vansh-codes** [comment]
Hello @ashutosh-rath02 , can you please check the post draft I have shared

**Comment by ashutosh-rath02** [comment]
Hey @vansh-codes I checked, can you make it like in bullet points what are the major features, then below it explaining about a little, don't make the post much larger keep it concise and to the point.

**Comment by vansh-codes** [comment]
Hiii @ashutosh-rath02, I have added draft2 just below the first draft, you can check here:
https://1drv.ms/w/s!Aq5VTv5cfNM2qDnTWbPCtioC94gF?e=tiB4wn

Please let me know as soon as possible as tomorrow I will be in train so wont be able to work because of network and many other issues while travelling

**Comment by ashutosh-rath02** [comment]
You have missed out a few things but I will add them. Have you used ChatGPT or any LLM? You can raise a PR with a small change in README somewhere so that I can give you the level 3

**Comment by vansh-codes** [comment]
> You have missed out a few things but I will add them. Have you used ChatGPT or any LLM? You can raise a PR with a small change in README somewhere so that I can give you the level 3

Ohh my bad, its really tough to go through the commits to know the changes and journey of the repo, also the repo has 340 commits 🤐
Yeah I used ChatGPT to check grammar and add good vocabulary as I am not really very good in choosing words sometimes so..
Yup raising a PR now

**Comment by vansh-codes** [comment]
Hey @ashutosh-rath02 Raised PR #440 
You can let me know for any changes in the PR
Thank you for level 3 🥳 
I hope you liked the post as it took time for me to go through the commits and note important changes ⌛

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #435 has been closed. Thank you for your contribution!
