### ISSUE TITLE
[Feature Request]: Change location in change theme icon

### ISSUE THREAD

**Issue by anniepauline** [ashutosh-rath02/git-re#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The user experience would be enhanced if the "Change Theme" icon was positioned at the top instead of the bottom, making it more accessible and convenient for users.

### Use Case

Easy accessibility: I can quickly switch between themes without scrolling down to the bottom.
Improved user experience: The prominent icon placement would make it more intuitive and user-friendly.
Time-saving: I can swiftly change the theme to suit my preferences or needs, saving time and effort.
Enhanced customization: The easy access to theme options would encourage me to explore and utilize different themes, making my experience more engaging and personalized.

### Benefits

Easy accessibility: I can quickly switch between themes without scrolling down to the bottom.
Improved user experience: The prominent icon placement would make it more intuitive and user-friendly.
Time-saving: I can swiftly change the theme to suit my preferences or needs, saving time and effort.
Enhanced customization: The easy access to theme options would encourage me to explore and utilize different themes, making my experience more engaging and personalized.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Let it be there.

**Comment by ashutosh-rath02** [comment]
Hello @anniepauline! Your issue #437 has been closed. Thank you for your contribution!
