### ISSUE TITLE
[Feature Request]: Display and update the GitHub repository's live star count.

### ISSUE THREAD

**Issue by anniepauline** [ashutosh-rath02/git-re#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When the user clicks the 'Star me' button, the website retrieves the current star count from GitHub and updates the display in real-time, reflecting the latest number of stars.

### Use Case

Given that a link to GitHub already exists, clicking the 'Star me' button to open the repository seems redundant. Instead, we can optimize the process by directly fetching the star count from GitHub and displaying it on our website, eliminating the need for an extra click.

### Benefits

**Convenience**: Users can view the star count without leaving the website or opening the GitHub repository.
**Real-time updates**: The star count is fetched directly from GitHub, ensuring accuracy and real-time updates.
Improved user experience: Streamlined process reduces clicks and makes it easier for users to view the star count.
**Enhanced visibility**: Displaying the star count prominently on the website highlights the project's popularity and community support.
**Increased engagement**: Easy access to the star count may encourage users to contribute to the project or star it on GitHub, fostering community growth.
**Reduced redundancy**: Eliminates the need for users to click the "Star me" button solely to view the star count, making the feature more efficient.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutosh-rath02** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by anniepauline** [comment]
On it!

**Comment by anniepauline** [comment]
Hey @ashutosh-rath02 do you want the on-click functionality to open the GitHub repo?
As of now, the button renders the live star count

**Comment by anniepauline** [comment]
Hey, lemme know if this is good, I'll make a PR

**Comment by ashutosh-rath02** [comment]
Hello @anniepauline! Your issue #438 has been closed. Thank you for your contribution!
