### ISSUE TITLE
UI betterment: Changer hover colour of the Github button 

### ISSUE THREAD

**Issue by Rakshit-gen** [ashutosh-rath02/git-re#44]
Github icon's text disappears when we hover on it
We can change the hover colour from black to grey to remove that effect.

Please assign this issue to me! I am a Gssoc contributor.

**Comment by ashutosh-rath02** [comment]
Go ahead @Rakshit-gen

**Comment by Rakshit-gen** [comment]
On it @ashutosh-rath02

**Comment by Rehan52004** [comment]
I want to work on it please assign me this issue.

**Comment by ashutosh-rath02** [comment]
Outdated
