### ISSUE TITLE
Create Contributor Page

### ISSUE THREAD

**Issue by Harshu467** [ashutosh-rath02/git-re#46]
Create a Contributor page to showcase all contributors

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by ashutosh-rath02** [comment]
We already have a section in our  github readme mentioning the contributors, no need of this now. You can explore our other issues and contribute
