### ISSUE TITLE
fix: Bug Change Twitter Logo to X

### ISSUE THREAD

**Issue by Harshu467** [ashutosh-rath02/git-re#47]
![image](https://github.com/ashutosh-rath02/git-re/assets/89975347/43f8eaff-928a-4f08-9bdd-bc3fa9e863fd)

As seen in photo , twitter icon is old , need to change to new one

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by ashutosh-rath02** [comment]
Go ahead @Harshu467

**Comment by Harshu467** [comment]
@ashutosh-rath02 
U did not assign me , plz assign it to me so I can work on it

**Comment by ashutosh-rath02** [comment]
@Harshu467 any updates?

**Comment by Harshu467** [comment]
@ashutosh-rath02  Give me today time , I have to submit project today so I was working on that will do it ASAP
