### ISSUE TITLE
feat: add Buy Me Coffee

### ISSUE THREAD

**Issue by Harshu467** [ashutosh-rath02/git-re#48]
We should Add Buy me Coffee Button so that project can get funds

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by ashutosh-rath02** [comment]
@Harshu467 where are you planning to add this button? Frontpage is already cluttered

**Comment by Harshu467** [comment]
@ashutosh-rath02 Well Buy Me Coffee Button will be auto button generated and it will be fix at bottom right of screen , I can share sample button how it can look like
![image](https://github.com/ashutosh-rath02/git-re/assets/89975347/632fff94-b7e5-470c-8767-6f2806586b2d)
![image](https://github.com/ashutosh-rath02/git-re/assets/89975347/7f26aa1f-448f-416a-addc-5baff5e928c5)
These are samples how button can look we can select color any whichever we want

**Comment by ashutosh-rath02** [comment]
Cool go ahead

**Comment by ashutosh-rath02** [comment]
@Harshu467 `.vasudev` You can reach out to me on discord for any creds you need.

**Comment by Harshu467** [comment]
@ashutosh-rath02 Can you share your discord link ?

**Comment by Harshu467** [comment]
@ashutosh-rath02 I have dm u via twitter share me script that I will need

**Comment by ashutosh-rath02** [comment]
> @ashutosh-rath02 Can you share your discord link ?

Discord username `.vasudev`

**Comment by Harshu467** [comment]
> > @ashutosh-rath02 Can you share your discord link ?
> 
> Discord username `.vasudev`

I have added request check out, if could share profile link it will be better

**Comment by ashutosh-rath02** [comment]
> > > @ashutosh-rath02 Can you share your discord link ?
> > 
> > 
> > Discord username `.vasudev`
> 
> I have added request check out, if could share profile link it will be better

Didnt receive anything neither on discord nor on twitter.
https://discordapp.com/users/519818032973873152

**Comment by ashutosh-rath02** [comment]
Any updates @Harshu467 ?

**Comment by ashutosh-rath02** [comment]
@Harshu467 updates?

**Comment by ashutosh-rath02** [comment]
Removing @Harshu467 due to inactivity
