### ISSUE TITLE
fix: blog link not functioning properly

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#51]
When trying to open the blog link, it will navigate to `https://git-re.vercel.app/resume` + `blog_url` instead of opening in the new tab. 

Please, assign this issue to me under GSSoC 24. 

Here's the demo of the issue.

https://github.com/ashutosh-rath02/git-re/assets/65452005/c6e8681d-f33b-4359-8cbc-189abba06e92

**Comment by ashutosh-rath02** [comment]
Have you located in code what's causing the issue? @dhairyathedev

**Comment by dhairyathedev** [comment]
yes, this occurs because the URLs in the blog lack the protocol `https` or `http`, rendering the current state of the blog URL non-absolute. 

Please assign this task to me, I will make a PR fixing the issue. @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
Ok @dhairyathedev You are gtg for the PR.
