### ISSUE TITLE
[BUG] : Validation required when searching for a github username

### ISSUE THREAD

**Issue by kshavp** [ashutosh-rath02/git-re#53]
When searching for a username, though the webapp seamlessly responds with a 404 Status Page. I found a bug when using only quotes ( *"* ) in the searchbar. 

Steps to Reproduce:

1. Go to https://[git-re](https://git-re.vercel.app/).vercel.app/
2. Login into the webapp.
3. Enter *"* or *""* in the search bar.
4. The webapp actually responds with a 200 Status Code and an actual resume page which can be seen in the attached media.

![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/0d4d226d-86f4-4f40-a6c1-7e684edb631c)

@ashutosh-rath02 I can work on this issue under GSSOC-24 if you could assign.

**Comment by ashutosh-rath02** [comment]
Hey @kshavp good eye there. You need to check if the username exists and then allow else you can display no username found. Look into working on this logic maybe?

**Comment by kshavp** [comment]
Sure, I think I can carry out this one.

**Comment by Sriver27** [comment]
I have got it what it takes. I can work on it. Please @ashutosh-rath02 can you assign the issue to me

**Comment by ashutosh-rath02** [comment]
Hello @kshavp! Your issue #53 has been closed. Thank you for your contribution!
