### ISSUE TITLE
Enhancment: Redesigned Landing Page

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#54]
There is issue with the footer. There is no space around the footer section, which makes it look plain.

Here's the current version of the footer 👇
<img width="1084" alt="Screenshot 2024-05-10 at 11 29 03 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/59c8847b-585a-46be-9f34-1a0d34adb4bd">

I have redesigned the footer and come up with two variants,
### Variant 1
<img width="1000" alt="Screenshot 2024-05-10 at 11 12 59 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/35eddf5e-c0f3-43e7-b017-46d83ea757ae">
<img width="1680" alt="Screenshot 2024-05-10 at 11 13 06 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/b143d7cb-2483-473f-9698-21826f6b4f64">

### Variant 2
<img width="1047" alt="Screenshot 2024-05-10 at 11 30 07 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/d458c598-217b-43eb-97a2-5a2d72f6dee6" >
<img width="1680" alt="Screenshot 2024-05-10 at 11 30 25 PM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/d03d9264-e925-4d12-aafd-adce0c1106c7">

Please assign, this to me. I will make the changes :)

**Comment by ashutosh-rath02** [comment]
Those looks good do you mind checking the issue for improving the whole UI? It seems to be a good fit for you😊

**Comment by dhairyathedev** [comment]
You mean, redesigning the landing page right? @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
Yup @dhairyathedev it will be a sub issue for that issue. Also you have a PR to be merged then only you can move onto the other

**Comment by dhairyathedev** [comment]
@ashutosh-rath02 I can redesign the landing page. Just to clarify, I have to create the redesigned landing page (PR) after you merge the previous PR #52

**Comment by ashutosh-rath02** [comment]
It's merged

**Comment by dhairyathedev** [comment]
You can assign this issue to me. @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
I will be closing this duplicate issue as I have tagged you in another issue where you can work
