### ISSUE TITLE
UI Enhancement : The text Inside the Generate button is getting overshadowed

### ISSUE THREAD

**Issue by SiddharthaArepalli** [ashutosh-rath02/git-re#56]
![Screenshot 2024-05-11 000515](https://github.com/ashutosh-rath02/git-re/assets/140429954/2598f282-6013-49ed-91dd-db00c426ad42)
I want improve the UI of the generate button in the dark theme

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02 assign me this under GSSOC'24

**Comment by ashutosh-rath02** [comment]
That's a feature it is disabled when nothing is typed in the search bar
