### ISSUE TITLE
feature: Add github profile comparison

### ISSUE THREAD

**Issue by ashutosh-rath02** [ashutosh-rath02/git-re#6]
As per our next feature plan, we will be allowing users to compare between their profiles.

**Comment by khadesamrudhi** [comment]
Please assign me this issue

**Comment by ashutosh-rath02** [comment]
Hey @khadesamrudhi can you please give me a walkthrough, how you are planning to solve this?

**Comment by ratishjain12** [comment]
@ashutosh-rath02 I can do this like we can compare stats by providing graphs charts of comparison using factors like contributions,stars achieved and maybe add a score based on this factors

Do let me know if you want to do in a certain way :)

**Comment by ashutosh-rath02** [comment]
Sure @ratishjain12 but one issue at a time. Which one you would like to work on first?

**Comment by ShubhiGulati** [comment]
Can you assign me this issue , i am planning to use the GitHub API to fetch information about each repository user want to compare. This includes data such as commits, branches, contributors, issues, pull requests, and more. At the end can calculate numerical differences directly or use algorithms to analyze textual data (e.g., code diffs, issue descriptions) in the form of table chart.

please assign it to me !!

**Comment by VanshikaSabharwal** [comment]
Hey, @ashutosh-rath02 .Can you assign me this issue . i can work on it.

**Comment by ashutosh-rath02** [comment]
@ShubhiGulati You want to work on this issue? @VanshikaSabharwal Let's wait for Shubhi. You can think of some new features. Would love to hear from contributors.

**Comment by ShubhiGulati** [comment]
yes sir i would love to do that

**Comment by ashutosh-rath02** [comment]
@ShubhiGulati any update?

**Comment by ashutosh-rath02** [comment]
https://discordapp.com/users/519818032973873152
Lets connect on discord for updates.

**Comment by cu8code** [comment]
Hey, I would like to work on this, I have some experience building with the GitHub API, I was thinking somethings very similar to this [website](https://nanoreview.net/en/cpu-compare/intel-core-i5-13500h-vs-amd-ryzen-7-7840hs) would love to connect and talk more @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
@cu8code we need to finalize the design for something like that first. Please give a mockup for that. Assigning you

**Comment by cu8code** [comment]
@ashutosh-rath02 I initially thought this was about comparing users, not sure what do you mean by comparing repository. I would love to create a mock-up in Figma, but I need a small brief about exactly what we are trying to achieve!

**Comment by cu8code** [comment]
@ashutosh-rath02 would love to discuss more with you on discord I have send you a request please accept it! `fokirthecat`

**Comment by ashutosh-rath02** [comment]
> @ashutosh-rath02 I initially thought this was about comparing users, not sure what do you mean by comparing repository. I would love to create a mock-up in Figma, but I need a small brief about exactly what we are trying to achieve!

You are right, it's between profile of two users

**Comment by cu8code** [comment]
@ratishjain12 here is a design I have been think about, [figma file](https://www.figma.com/design/nRenT1mZNLqwqY48TTYNww/git-re?node-id=0%3A1&t=AMKuEYOn6LTNREQ7-1) also I can not reach you on discord, can you tell me your username, the link you provided has expired I guess

**Comment by ashutosh-rath02** [comment]
@cu8code that looks great, let's discuss some more contents over discord.

**Comment by ashutosh-rath02** [comment]
@ratishjain12 @dhairyathedev @NilanchalaPanda @RoopsagarK @growupanand @kshavp As you guys have already contributed to the project, your suggestions would be great regarding this section. We are creating a complete new section other that resume.

**Comment by kshavp** [comment]
@ashutosh-rath02 I would suggest that we can define a few parameters of comparison just like @ShubhiGulati mentioned: commits, branches, contributors, issues, pull requests, and more.

Storing the objects of stats and using any graph library to visualize them. Personally, I would have preferred a radar chart which can be seen in the media below. You can use [Recharts](https://recharts.org/en-US/examples/SpecifiedDomainRadarChart) to achieve the same.

![image](https://github.com/ashutosh-rath02/git-re/assets/95236968/aac5ae0a-e1dd-4e71-8c37-81ee44a49eb7)

**Comment by ashutosh-rath02** [comment]
@cu8code any updates?

**Comment by Sid-80** [comment]
I am willing to work on this issue!

**Comment by ashutosh-rath02** [comment]
Go ahead @Sid-80 we will need some mockups before that. Let's chat on discord. My username is `.vasudev`

**Comment by ashutosh-rath02** [comment]
@Swastik19Nit Go ahead raise a PR

**Comment by Swastik19Nit** [comment]
i had done this based  on the score generated in the leaderboard the winner is marked green. @ashutosh-rath02 
![image](https://github.com/ashutosh-rath02/git-re/assets/122457803/27b3704a-8007-43a7-915b-ad0fe8c984f4)
![image](https://github.com/ashutosh-rath02/git-re/assets/122457803/e1da044b-2913-4163-ba24-c987d1b50ab0)
![image](https://github.com/ashutosh-rath02/git-re/assets/122457803/30abe7f2-e8f2-42ad-916b-2daac9d9e52f)
Users are already in the leaderboard

**Comment by ashutosh-rath02** [comment]
Ok @Swastik19Nit this seems good for starting phase. Can you show the dark mode view and also do you have any other plans to improve this? 
You can take responsibility of this whole component.

**Comment by Swastik19Nit** [comment]
this is what looks in dark mode 

https://github.com/ashutosh-rath02/git-re/assets/122457803/71c2c493-bae5-45b8-9df0-7f923616f42d

**Comment by Swastik19Nit** [comment]
@ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
@Swastik19Nit raise a PR please

**Comment by ashutosh-rath02** [comment]
Hello @ashutosh-rath02! Your issue #6 has been closed. Thank you for your contribution!
