### ISSUE TITLE
The sidebar of the resume preview page should be sticky

### ISSUE THREAD

**Issue by growupanand** [ashutosh-rath02/git-re#61]
The sidebar isn't sticky right now. So, the sidebar checkboxes are hidden if the user scrolls down the page to view other sections. For instance, the contribution section's `Show Contribution Graph` checkbox is currently inaccessible.

**Screenshots**

Before scrolling page
<img width="1728" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/29487686/18af5013-7be8-4e47-a3b8-376665068038">

After Scrolling page
<img width="1728" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/29487686/08f33adf-38e9-4183-973d-e4ed4be878ac">

**Comment by growupanand** [comment]
@ashutosh-rath02 , assign this to me so that I can start working on it.

**Comment by ashutosh-rath02** [comment]
Go ahead @growupanand will assign you shortly
