### ISSUE TITLE
Need to work on error handling and also add a error page

### ISSUE THREAD

**Issue by Sriver27** [ashutosh-rath02/git-re#62]
When I was crawling over the website and fetching for my github username api rate limit reached

<img width="1512" alt="image" src="https://github.com/ashutosh-rath02/git-re/assets/75061992/273f5d98-a0f7-474a-90f6-242db1bcf5d3">

@ashutosh-rath02 Please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
What are you planning to do. Please give me a workflow.

**Comment by Sriver27** [comment]
Upon successful response status of network call, we will proceed with things further otherwise we would be going with an error function which will show a error placeholder page with relevant info for the error to the user

**Comment by ashutosh-rath02** [comment]
Ok go ahead @Sriver27

**Comment by ashutosh-rath02** [comment]
@Sriver27 update?

**Comment by IbrahimDev00** [comment]
@ashutosh-rath02 Please assign this issue to me as well. 
Thank you!

**Comment by IbrahimDev00** [comment]
@ashutosh-rath02 Update: The logic has been implemented with code, will test it extensively and open a PR by tomorrow morning.

**Comment by ashutosh-rath02** [comment]
Hello @Sriver27! Your issue #62 has been closed. Thank you for your contribution!
