### ISSUE TITLE
NOT RESPONSIVE AND NEED SOME SMALL UI CHANGES

### ISSUE THREAD

**Issue by Venkatknight2295** [ashutosh-rath02/git-re#74]
![image](https://github.com/ashutosh-rath02/git-re/assets/118790430/c1a27c9c-7e5e-4d05-893b-dedcf6da2c78)
the site is not properly responsive enough assign me this task i will make it responsive and make minor UI changes @ashutosh-rath02 @growupanand @ratishjain12 @dhairyathedev

**Comment by ashutosh-rath02** [comment]
Sure @Venkatknight2295 Go ahead with the issue and make sure you have some before vs after photos ready so that we can compare the changes

**Comment by ashutosh-rath02** [comment]
@Venkatknight2295 any updates?

**Comment by ashutosh-rath02** [comment]
@Venkatknight2295 updates?

**Comment by AMISH-KHAN** [comment]
hey @ashutosh-rath02 I would like to work on this

**Comment by ashutosh-rath02** [comment]
@AMISH-KHAN go ahead

**Comment by AMISH-KHAN** [comment]
@ashutosh-rath02 is this what we are looking for?


https://github.com/ashutosh-rath02/git-re/assets/123164129/a0a2d6d6-2fbc-4f22-96ba-162132f76caa

**Comment by ashutosh-rath02** [comment]
Do it for the mobile views too

**Comment by ashutosh-rath02** [comment]
Hello @Venkatknight2295! Your issue #74 has been closed. Thank you for your contribution!
