### ISSUE TITLE
Enhancements and Corrections for README.md

### ISSUE THREAD

**Issue by thevijayshankersharma** [ashutosh-rath02/git-re#80]
Description:
This issue is raised to propose enhancements and corrections for the README.md file of the GitHub Resume Generator project. The current README contains valuable information but could benefit from improvements in clarity, consistency, and completeness.

As a participant of GSSoC (GirlScript Summer of Code), I'm interested in taking on this issue to contribute to the project's improvement. 

Assign this issue to me.

**Comment by ashutosh-rath02** [comment]
Can you tell what things need to be changed in README?

**Comment by thevijayshankersharma** [comment]
Hi @ashutosh-rath02,

Thank you for reaching out. After reviewing the README.md file, I've identified a few areas where we can make improvements for clarity and consistency:

Introduction:

Original: "Simply enter a GitHub username, and the application will create a resume based on the user's contributions and projects."
Suggested: "By entering a GitHub username, this web application generates a professional resume based on the user's contributions and projects."
Minor typo:

Original: "To know to more project"
Suggested: "To know more about the project"
Setup and Installation:

"Set Up your Database" could be "Setting Up Your Database" for better readability.
Capitalization:

Consider capitalizing the first letter of each word in headings for consistency.

I believe these adjustments will enhance the readability and clarity of the README. Let me know if you agree with these changes or if you have any further suggestions.

**Comment by ashutosh-rath02** [comment]
Ok @thevijayshankersharma , go ahead

**Comment by thevijayshankersharma** [comment]
I have updated the README.md in "readme-enhancements" branch, could you tell what should I do next ?

**Comment by ashutosh-rath02** [comment]
Raise a PR @thevijayshankersharma

**Comment by thevijayshankersharma** [comment]
@ashutosh-rath02 without merging it with main branch ?
