### ISSUE TITLE
refactor: migrate from mongodb to Supabase for recent users

### ISSUE THREAD

**Issue by dhairyathedev** [ashutosh-rath02/git-re#81]
### Why?

As we are using Supabase for the authentication. We can use Supabase to store the recent users. This keeps whole data on the single architecture which makes it easier to:
- Easy to maintain
- Easy scaling up
- Better performance
- Better security

I can help migrate from MongoDB to Supabase. Please assign this task to me.

**Comment by ashutosh-rath02** [comment]
Go ahead @dhairyathedev
