### ISSUE TITLE
Docs - Add Table of contents and 'Featured In' Section to readme

### ISSUE THREAD

**Issue by SpaciousCoder78** [ashutosh-rath02/git-re#83]
Readme section seems to be missing a table of contents section and I would also like to add a featured in section that shows the open source programmes that this project has been a part of.

Please assign this issue to me under Gssoc 24 and I shall begin the work immediately once assigned.

**Comment by ashutosh-rath02** [comment]
Sure @SpaciousCoder78 go ahead. Please provide the estimated time to finish this

**Comment by SpaciousCoder78** [comment]
I can do this in 15-20 minutes

**Comment by SpaciousCoder78** [comment]
The suggested features have been added and merged into the repository. Thanks for giving me this opportunity. I'll go through your project and suggest more features.
