### ISSUE TITLE
Hover effect to social media icons 

### ISSUE THREAD

**Issue by SalehaTabassum** [ashutosh-rath02/git-re#84]
I would like to hover effect to social media icons to make them look responsive 

@ashutosh-rath02  please assign this issue to me under GSSOC 2024 and add necessary labels

**Comment by ashutosh-rath02** [comment]
Sure but please provide a screenshot of before and after. And time you will take to finish the issue

**Comment by SalehaTabassum** [comment]
@ashutosh-rath02 

![Screenshot_2024-05-12-20-33-37-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ashutosh-rath02/git-re/assets/169278740/842dde9e-ae42-414e-abe9-edf6072251a4)
Currently the social media icons look like these

![Screenshot_2024-05-12-20-29-29-10_f9ee0578fe1cc94de7482bd41accb329](https://github.com/ashutosh-rath02/git-re/assets/169278740/e8fc4fee-b0f6-4bc4-984b-3c7758c55de8)
I would like to create this kind of hover effect to social media icons 
I will finish this issue within 2 days 

Please assign this issue to me under GSSOC 2024 and add necessary labels to it

**Comment by SalehaTabassum** [comment]
> It should match our color theme @SalehaTabassum. Go for it

Ok sir thank you

**Comment by ashutosh-rath02** [comment]
Stale

**Comment by ashutosh-rath02** [comment]
Hello @SalehaTabassum! Your issue #84 has been closed. Thank you for your contribution!
