### ISSUE TITLE
Regrading  website animations 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [ashutosh-rath02/git-re#88]
hi i am Ram #gssoc24
i want to add some animations in your website which looks good and User interactive
tech stack to be used
-AOS.js
-ityped.js
etc

**Comment by ashutosh-rath02** [comment]
Hey there @RamakrushnaBiswal . If it's framer motion then only we can plan something

**Comment by RamakrushnaBiswal** [comment]
@ashutosh-rath02 yh sir

**Comment by ashutosh-rath02** [comment]
Sure @RamakrushnaBiswal please work on it and give me a preview video first and time you will require to finish this.

**Comment by RamakrushnaBiswal** [comment]
@ashutosh-rath02 ok sir

**Comment by ashutosh-rath02** [comment]
Stale

**Comment by ashutosh-rath02** [comment]
Hello @RamakrushnaBiswal! Your issue #88 has been closed. Thank you for your contribution!
