### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [ashutosh-rath02/git-re#89]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started. The current README is not visually appealing and also lacks some begineer friendly contribution start guide.

hey @ashutosh-rath02  , please assign this issue to me.

**Comment by ashutosh-rath02** [comment]
The README is well structured according to the needs to beginners with every step required for setup

**Comment by jinx-vi-0** [comment]
hey @ashutosh-rath02, I propose to make it more visually appealing by adding badges for tech stack, visiter count, issue count, fork count and other items.

**Comment by ashutosh-rath02** [comment]
Can you give me a preview regarding what you are planning to do?

**Comment by jinx-vi-0** [comment]
hey @ashutosh-rath02 , Below are some samples

![image](https://github.com/ashutosh-rath02/git-re/assets/120160355/1af7fc9c-3b2b-45ca-88ab-bc4f9a07532d)
![image](https://github.com/ashutosh-rath02/git-re/assets/120160355/726c4e84-69e8-49aa-b34f-014a6b3f4bd1)

**Comment by ashutosh-rath02** [comment]
Ok @jinx-vi-0 let's give this a try.

**Comment by jinx-vi-0** [comment]
hey @ashutosh-rath02 , I have made a pr please check it and let me know for any feedback.
