### ISSUE TITLE
[BUG]: Blog Link/Portfolio Link Not Functioning Correctly

### ISSUE THREAD

**Issue by RashidSiddiqui2004** [ashutosh-rath02/git-re#96]
The **_portfolio links_** added by users on their profiles are _**not redirecting correctly on the website**_. Upon investigation, it has been found that the links are being processed incorrectly, leading to broken or inaccessible portfolio pages for users.

Steps to Reproduce:

1. Navigate to any user profile on the website.
2. Look for the "Portfolio" or "Website" section in the user's profile information.
3. Click on the portfolio link provided.

For reference, take a look at this profile:
![issu10](https://github.com/ashutosh-rath02/git-re/assets/124426004/9e7268b9-c077-4f33-be21-09147edbba32)

Portfolio link re-directs to wrong page:
![iss11](https://github.com/ashutosh-rath02/git-re/assets/124426004/44769c83-d0a6-47ba-9454-e55d89b3c999)

**Comment by RashidSiddiqui2004** [comment]
@ashutosh-rath02 Pls assign this task to me under GSSOC'24.😊✨

**Comment by ashutosh-rath02** [comment]
https://github.com/ashutosh-rath02/git-re/pull/52
@RashidSiddiqui2004 Look into the changes we made here. Think what changes we can do to accommodate both type of links

**Comment by RashidSiddiqui2004** [comment]
@ashutosh-rath02 I have resolved the issue 📌, pls look into it. The issue was with wrong pre-processing of the URL.

**Comment by dhairyathedev** [comment]
@RashidSiddiqui2004  I have mentioned the changes in the PR #97

**Comment by ashutosh-rath02** [comment]
@RashidSiddiqui2004 have you checked the above comment?

**Comment by RashidSiddiqui2004** [comment]
@ashutosh-rath02 Yes, I've checked above comment, but there's is no mentions in PR #97 by @dhairyathedev .
The PR merged with reference to  #52  doesn't actually solve the issue when URL stored in the Github profile is actually contains, 'https://' so we need to remove that, and just link that profile URL as it is.

**Comment by RashidSiddiqui2004** [comment]
@ashutosh-rath02 I have updated the re-direction logic, pls check. 😊

**Comment by ashutosh-rath02** [comment]
@all-contributors add @RashidSiddiqui2004 for code
